// 🚀 Auto-generated by scripts/generate-routes.ts
// ⚠️  DO NOT EDIT MANUALLY
// Generated at: 2026-02-10T19:29:54.036Z
//
// Convention:
// - page.tsx   = Route page
// - layout.tsx = Layout wrapper
// - loading.tsx/error.tsx are discovered but not emitted unless you wire them up explicitly.

import { lazy } from 'react';

const layout_tsx = lazy(() => import('@/pages/layout.tsx'));
const auth_layout_tsx = lazy(() => import('@/pages/(public)/layout'));
const main_layout_tsx = lazy(() => import('@/pages/(private)/layout'));
const page_tsx = lazy(() => import('@/pages/page.tsx'));
const auth_forgot_page_tsx = lazy(() => import('@/pages/(public)/forgot/page'));
const auth_login_page_tsx = lazy(() => import('@/pages/(public)/login/page'));
const auth_reset_page_tsx = lazy(() => import('@/pages/(public)/reset/page'));
const main_dashboard_page_tsx = lazy(() => import('@/pages/(private)/dashboard/page'));
const main_configurations_branches_page_tsx = lazy(() => import('@/pages/(private)/(configurations)/branches/page'));
const main_configurations_locations_page_tsx = lazy(() => import('@/pages/(private)/(configurations)/locations/page'));
const main_operations_parcel_page_tsx = lazy(() => import('@/pages/(private)/operations/parcel/page'));

// React Router v7 routes
export const routes = [
  {
    path: '/',
    Component: layout_tsx,
    children: [
      { index: true, Component: page_tsx },
    ],
  },
  {
    path: '/',
    Component: auth_layout_tsx,
    children: [
      { path: 'forgot', Component: auth_forgot_page_tsx },
      { path: 'login', Component: auth_login_page_tsx },
      { path: 'reset', Component: auth_reset_page_tsx },
    ],
  },
  {
    path: '/',
    Component: main_layout_tsx,
    children: [
      { path: 'branches', Component: main_configurations_branches_page_tsx },
      { path: 'dashboard', Component: main_dashboard_page_tsx },
      { path: 'locations', Component: main_configurations_locations_page_tsx },
      { path: 'operations/parcel', Component: main_operations_parcel_page_tsx },
    ],
  },
];
