// 🚀 Auto-generated by scripts/generate-routes.ts
// ⚠️  DO NOT EDIT MANUALLY
// Generated at: 2026-02-08T21:47:11.029Z
//
// Convention:
// - page.tsx   = Route page
// - layout.tsx = Layout wrapper
// - loading.tsx/error.tsx are discovered but not emitted unless you wire them up explicitly.

import { lazy } from 'react';

const layout_tsx = lazy(() => import('@/pages/layout.tsx'));
const auth_layout_tsx = lazy(() => import('@/pages/(auth)/layout.tsx'));
const main_layout_tsx = lazy(() => import('@/pages/(main)/layout.tsx'));
const page_tsx = lazy(() => import('@/pages/page.tsx'));
const auth_forgot_page_tsx = lazy(() => import('@/pages/(auth)/forgot/page.tsx'));
const auth_login_page_tsx = lazy(() => import('@/pages/(auth)/login/page.tsx'));
const auth_reset_page_tsx = lazy(() => import('@/pages/(auth)/reset/page.tsx'));
const main_dashboard_page_tsx = lazy(() => import('@/pages/(main)/dashboard/page.tsx'));
const main_configurations_branches_page_tsx = lazy(() => import('@/pages/(main)/(configurations)/branches/page.tsx'));
const main_configurations_locations_page_tsx = lazy(() => import('@/pages/(main)/(configurations)/locations/page.tsx'));
const main_operations_parcel_page_tsx = lazy(() => import('@/pages/(main)/operations/parcel/page.tsx'));

// React Router v7 routes
export const routes = [
  {
    path: '/',
    Component: layout_tsx,
    children: [
      { index: true, Component: page_tsx },
    ],
  },
  {
    path: '/',
    Component: auth_layout_tsx,
    children: [
      { path: 'forgot', Component: auth_forgot_page_tsx },
      { path: 'login', Component: auth_login_page_tsx },
      { path: 'reset', Component: auth_reset_page_tsx },
    ],
  },
  {
    path: '/',
    Component: main_layout_tsx,
    children: [
      { path: 'branches', Component: main_configurations_branches_page_tsx },
      { path: 'dashboard', Component: main_dashboard_page_tsx },
      { path: 'locations', Component: main_configurations_locations_page_tsx },
      { path: 'operations/parcel', Component: main_operations_parcel_page_tsx },
    ],
  },
];
