const catalog = [
  // RBAC / Users
  ['CanReadUsers', 'View users', 'Users'],
  ['CanCreateUsers', 'Create users', 'Users'],
  ['CanUpdateUsers', 'Update users', 'Users'],
  ['CanDeleteUsers', 'Delete users', 'Users'],
  ['CanReadRoles', 'View roles', 'RBAC'],
  ['CanCreateRoles', 'Create roles', 'RBAC'],
  ['CanUpdateRoles', 'Update roles', 'RBAC'],
  ['CanDeleteRoles', 'Delete roles', 'RBAC'],
  ['CanReadPermissions', 'View permission catalog', 'RBAC'],
  ['CanGetRolePermissions', 'Get role permissions', 'RBAC'],
  ['CanSetRolePermissions', 'Set role permissions', 'RBAC'],

  // Branches / Locations / Customers / Cards
  ['CanReadBranches', 'List and view branches', 'Branches'],
  ['CanCreateBranches', 'Create branches', 'Branches'],
  ['CanUpdateBranches', 'Update branches', 'Branches'],
  ['CanDeleteBranches', 'Delete branches', 'Branches'],
  ['CanReadLocations', 'List and view locations', 'Locations'],
  ['CanCreateLocations', 'Create locations', 'Locations'],
  ['CanUpdateLocations', 'Update locations', 'Locations'],
  ['CanDeleteLocations', 'Delete locations', 'Locations'],
  ['CanReadWarehouses', 'List and view warehouses', 'Warehouses'],
  ['CanCreateWarehouses', 'Create warehouses', 'Warehouses'],
  ['CanUpdateWarehouses', 'Update warehouses', 'Warehouses'],
  ['CanDeleteWarehouses', 'Delete warehouses', 'Warehouses'],
  ['CanReadCustomers', 'List and view customers', 'Customers'],
  ['CanCreateCustomers', 'Create customers', 'Customers'],
  ['CanUpdateCustomers', 'Update customers', 'Customers'],
  ['CanDeleteCustomers', 'Delete customers', 'Customers'],
  ['CanReadCards', 'List and view cards', 'Cards'],
  ['CanCreateCards', 'Create cards', 'Cards'],
  ['CanUpdateCards', 'Update cards', 'Cards'],
  ['CanDeleteCards', 'Delete cards', 'Cards'],

  // Shipments / Parcels / Consignments / Grouping
  ['CanReadShipments', 'List shipments', 'Shipments'],
  ['CanCreateShipments', 'Create shipments', 'Shipments'],
  ['CanUpdateShipments', 'Update shipments', 'Shipments'],
  ['CanDeleteShipments', 'Delete shipments', 'Shipments'],
  ['CanCreateBookingWithParcels', 'Create booking with parcels', 'Shipments'],
  ['CanReadParcels', 'List and view parcels', 'Shipments'],
  ['CanReadParcelSendingModule', 'View parcel sending module', 'Shipments'],
  ['CanReadParcelReceivingModule', 'View parcel receiving module', 'Shipments'],
  ['CanReadParcelOutgoing', 'View in-transit outgoing parcels', 'Shipments'],
  ['CanReadParcelIncoming', 'View in-transit incoming parcels', 'Shipments'],
  ['CanReadParcelScan', 'View and use parcel scan-to-receive', 'Shipments'],
  ['CanCreateParcels', 'Create parcels', 'Shipments'],
  ['CanUpdateParcels', 'Update parcels', 'Shipments'],
  ['CanDeleteParcels', 'Delete parcels', 'Shipments'],
  [
    'CanSoftDeleteParcelsAndPayments',
    'Soft delete parcels and soft delete (void) linked payments with reason',
    'Shipments',
  ],
  ['CanReadConsignments', 'List and view consignments', 'Shipments'],
  ['CanCreateConsignments', 'Create consignments', 'Shipments'],
  ['CanUpdateConsignments', 'Update consignments', 'Shipments'],
  ['CanDeleteConsignments', 'Delete consignments', 'Shipments'],
  ['CanAutoGroupConsignments', 'Auto group consignments', 'Shipments'],

  // Cashiers / Shifts
  ['CanReadCashierSessionTypes', 'List cashier session types', 'Cashiers'],
  ['CanCreateCashierSessionTypes', 'Create cashier session types', 'Cashiers'],
  ['CanReadCashierSessions', 'List and view cashier sessions', 'Cashiers'],
  ['CanOpenCashierSessions', 'Open cashier sessions', 'Cashiers'],
  ['CanReopenCashierSessions', 'Reopen cashier sessions on same day', 'Cashiers'],
  ['CanCloseCashierSessions', 'Close cashier sessions', 'Cashiers'],
  ['CanListShiftSessions', 'List shift sessions', 'Shifts'],
  ['CanOpenShiftSession', 'Open shift session', 'Shifts'],
  ['CanCloseShiftSession', 'Close shift session', 'Shifts'],
  ['CanApproveShiftSession', 'Approve shift session', 'Shifts'],
  ['CanGetShiftReport', 'View shift report', 'Shifts'],
  ['CanGetActiveShiftByBranch', 'View active shift by branch', 'Shifts'],

  // Deliveries
  ['CanDispatchForDelivery', 'Dispatch parcels for delivery', 'Deliveries'],
  ['CanCreateDeliveryOrder', 'Create delivery order', 'Deliveries'],
  ['CanCreatePickupQueue', 'Create pickup queue entries', 'Deliveries'],
  ['CanReadSenderPickupQueue', 'View sender pickup queue board', 'Deliveries'],
  ['CanReadReceiverPickupQueue', 'View receiver pickup queue board', 'Deliveries'],
  ['CanReadCallCenterParcelStatus', 'View call center parcel status', 'Deliveries'],
  ['CanReadRiderCurrentParcels', 'View rider current parcels', 'Deliveries'],
  ['CanReadRiderHistory', 'View rider parcel history', 'Deliveries'],
  ['CanCompleteOfficePickup', 'Complete office pickup', 'Deliveries'],
  ['CanMarkDoorstepCalled', 'Mark doorstep called', 'Deliveries'],
  ['CanAssignDoorstepRider', 'Assign doorstep rider', 'Deliveries'],
  ['CanMarkOutForDelivery', 'Mark out for delivery', 'Deliveries'],
  ['CanCompleteDoorstepDelivery', 'Complete doorstep delivery', 'Deliveries'],
  ['CanReadParcelInternalTransfers', 'List and view parcel internal transfers', 'Deliveries'],
  ['CanCreateParcelInternalTransfers', 'Create parcel internal transfers', 'Deliveries'],
  ['CanAcknowledgeParcelInternalTransfers', 'Acknowledge parcel internal transfers', 'Deliveries'],
  ['CanCancelParcelInternalTransfers', 'Cancel parcel internal transfers', 'Deliveries'],

  // Payments / Accounting
  ['CanCreatePayments', 'Create payments', 'Payments'],
  ['CanCreateSenderPayments', 'Collect sender payments', 'Payments'],
  ['CanCreateReceiverPayments', 'Collect receiver payments', 'Payments'],
  ['CanReadPayments', 'List and view payments', 'Payments'],
  ['CanReadAccounting', 'View accounting pages, lists, and reports', 'Accounting'],
  ['CanReadAccountingSetup', 'View accounting setup masters', 'Accounting'],
  ['CanCreateAccountingSetup', 'Create accounting setup masters', 'Accounting'],
  ['CanUpdateAccountingSetup', 'Update accounting setup masters', 'Accounting'],
  ['CanDeleteAccountingSetup', 'Delete accounting setup masters', 'Accounting'],
  ['CanReadAccountingAccounts', 'View accounting setup accounts', 'Accounting'],
  ['CanCreateAccountingAccounts', 'Create accounting setup accounts', 'Accounting'],
  ['CanUpdateAccountingAccounts', 'Update accounting setup accounts', 'Accounting'],
  ['CanDeleteAccountingAccounts', 'Delete accounting setup accounts', 'Accounting'],
  ['CanReadAccountingExpenseCategories', 'View accounting setup expense categories', 'Accounting'],
  [
    'CanCreateAccountingExpenseCategories',
    'Create accounting setup expense categories',
    'Accounting',
  ],
  [
    'CanUpdateAccountingExpenseCategories',
    'Update accounting setup expense categories',
    'Accounting',
  ],
  [
    'CanDeleteAccountingExpenseCategories',
    'Delete accounting setup expense categories',
    'Accounting',
  ],
  ['CanReadAccountingApprovalPolicies', 'View accounting setup approval policies', 'Accounting'],
  [
    'CanCreateAccountingApprovalPolicies',
    'Create accounting setup approval policies',
    'Accounting',
  ],
  [
    'CanUpdateAccountingApprovalPolicies',
    'Update accounting setup approval policies',
    'Accounting',
  ],
  [
    'CanDeleteAccountingApprovalPolicies',
    'Delete accounting setup approval policies',
    'Accounting',
  ],
  ['CanReadAccountingBankAccounts', 'View accounting setup bank accounts', 'Accounting'],
  ['CanCreateAccountingBankAccounts', 'Create accounting setup bank accounts', 'Accounting'],
  ['CanUpdateAccountingBankAccounts', 'Update accounting setup bank accounts', 'Accounting'],
  ['CanDeleteAccountingBankAccounts', 'Delete accounting setup bank accounts', 'Accounting'],
  ['CanReadAccountingTaxProfiles', 'View accounting setup tax profiles', 'Accounting'],
  ['CanCreateAccountingTaxProfiles', 'Create accounting setup tax profiles', 'Accounting'],
  ['CanUpdateAccountingTaxProfiles', 'Update accounting setup tax profiles', 'Accounting'],
  ['CanDeleteAccountingTaxProfiles', 'Delete accounting setup tax profiles', 'Accounting'],
  ['CanReadAccountingTaxComponents', 'View accounting setup tax components', 'Accounting'],
  ['CanCreateAccountingTaxComponents', 'Create accounting setup tax components', 'Accounting'],
  ['CanUpdateAccountingTaxComponents', 'Update accounting setup tax components', 'Accounting'],
  ['CanDeleteAccountingTaxComponents', 'Delete accounting setup tax components', 'Accounting'],
  ['CanCreateTaxFilingPeriod', 'Create tax filing period', 'Accounting'],
  ['CanMarkTaxFilingPeriodUnderReview', 'Mark tax filing period under review', 'Accounting'],
  ['CanSubmitTaxFilingPeriod', 'Submit tax filing period', 'Accounting'],
  ['CanCloseTaxFilingPeriod', 'Close tax filing period', 'Accounting'],
  ['CanMarkTaxItemReadyForFiling', 'Mark tax item ready for filing', 'Accounting'],
  ['CanMarkTaxItemFiled', 'Mark tax item filed', 'Accounting'],
  ['CanExcludeTaxItemFromFiling', 'Exclude tax item from filing', 'Accounting'],
  ['CanCreateDailyCashConfirmation', 'Create daily cash confirmation', 'Accounting'],
  ['CanConfirmDailyCashConfirmation', 'Confirm daily cash confirmation', 'Accounting'],
  ['CanPostDailyCashConfirmation', 'Post daily cash confirmation', 'Accounting'],
  ['CanCreateExpenseRequest', 'Create expense request', 'Accounting'],
  ['CanSubmitExpenseRequest', 'Submit expense request', 'Accounting'],
  ['CanApproveExpenseRequest', 'Approve expense request', 'Accounting'],
  ['CanRejectExpenseRequest', 'Reject expense request', 'Accounting'],
  ['CanPayExpenseRequest', 'Pay expense request', 'Accounting'],
  ['CanPostExpenseRequest', 'Post expense request', 'Accounting'],
  ['CanComputeTaxes', 'Compute taxes', 'Accounting'],
  ['CanReadAccountingManualEntries', 'View manual accounting entries page', 'Accounting'],
  ['CanCreateAccountingManualEntries', 'Create manual accounting entries', 'Accounting'],
  [
    'CanApproveAccountingManualEntries',
    'Approve and post manual accounting entries above threshold',
    'Accounting',
  ],

  // Inventory
  ['CanReadInventoryOverview', 'View inventory overview dashboard', 'Inventory'],
  ['CanReadProducts', 'View products pages', 'Inventory'],
  ['CanReadProductCategories', 'View product category pages', 'Inventory'],
  ['CanReadInventoryLocations', 'View inventory location pages', 'Inventory'],
  ['CanReadStockLevels', 'View stock levels pages', 'Inventory'],
  ['CanReadStockMovements', 'View stock movement pages', 'Inventory'],
  ['CanReadStockAdjustments', 'View stock adjustment pages', 'Inventory'],
  ['CanReadStockTransfers', 'View stock transfer pages', 'Inventory'],
  ['CanListProductCategories', 'List product categories', 'Inventory'],
  ['CanGetProductCategory', 'Get product category', 'Inventory'],
  ['CanCreateProductCategory', 'Create product category', 'Inventory'],
  ['CanUpdateProductCategory', 'Update product category', 'Inventory'],
  ['CanDeleteProductCategory', 'Delete product category', 'Inventory'],
  ['CanListProducts', 'List products', 'Inventory'],
  ['CanGetProduct', 'Get product', 'Inventory'],
  ['CanCreateProduct', 'Create product', 'Inventory'],
  ['CanUpdateProduct', 'Update product', 'Inventory'],
  ['CanDeleteProduct', 'Delete product', 'Inventory'],
  ['CanListInventoryLocations', 'List inventory locations', 'Inventory'],
  ['CanGetInventoryLocation', 'Get inventory location', 'Inventory'],
  ['CanCreateInventoryLocation', 'Create inventory location', 'Inventory'],
  ['CanUpdateInventoryLocation', 'Update inventory location', 'Inventory'],
  ['CanDeleteInventoryLocation', 'Delete inventory location', 'Inventory'],
  ['CanListStockLevels', 'List stock levels', 'Inventory'],
  ['CanGetStockLevel', 'Get stock level', 'Inventory'],
  ['CanListStockMovements', 'List stock movements', 'Inventory'],
  ['CanCreateStockMovement', 'Create stock movement', 'Inventory'],
  ['CanListStockAdjustments', 'List stock adjustments', 'Inventory'],
  ['CanCreateStockAdjustment', 'Create stock adjustment', 'Inventory'],
  ['CanListStockTransfers', 'List stock transfers', 'Inventory'],
  ['CanGetStockTransfer', 'Get stock transfer', 'Inventory'],
  ['CanCreateStockTransfer', 'Create stock transfer', 'Inventory'],
  ['CanUpdateStockTransfer', 'Update stock transfer', 'Inventory'],
  ['CanGetLowStockReport', 'View low stock report', 'Inventory'],
  ['CanGetMovementHistory', 'View movement history report', 'Inventory'],

  // Reports / Audit / HR / Payroll / Geo
  ['CanGetCashierPerformanceReport', 'View cashier performance report', 'Reports'],
  ['CanGetShiftRevenueReport', 'View shift revenue report', 'Reports'],
  ['CanGetBranchProfitabilityReport', 'View branch profitability report', 'Reports'],
  ['CanGetCreditExposureReport', 'View credit exposure report', 'Reports'],
  ['CanGetOutstandingToBePaidReport', 'View outstanding to-be-paid report', 'Reports'],
  ['CanGetParcelStatusSummaryReport', 'View parcel status summary report', 'Reports'],
  ['CanViewReportFinancialTrialBalance', 'View report: Trial Balance', 'Reports'],
  ['CanViewReportFinancialAccountStatement', 'View report: Account Statement', 'Reports'],
  ['CanViewReportFinancialIncomeStatement', 'View report: Income Statement', 'Reports'],
  ['CanViewReportFinancialProfitLoss', 'View report: Profit & Loss', 'Reports'],
  ['CanViewReportFinancialBalanceSheet', 'View report: Balance Sheet', 'Reports'],
  ['CanViewReportFinancialCashFlow', 'View report: Cash Flow', 'Reports'],
  ['CanViewReportFinancialGeneralLedger', 'View report: General Ledger', 'Reports'],
  ['CanViewReportFinancialJournalListing', 'View report: Journal Listing', 'Reports'],
  ['CanViewReportFinancialAccountActivity', 'View report: Account Activity', 'Reports'],
  ['CanViewReportBranchMonthlySummary', 'View report: Monthly Branch Summary', 'Reports'],
  ['CanViewReportBranchRevenue', 'View report: Branch Revenue', 'Reports'],
  ['CanViewReportBranchExpense', 'View report: Branch Expense', 'Reports'],
  ['CanViewReportBranchProfitSummary', 'View report: Branch Profit Summary', 'Reports'],
  ['CanViewReportBranchPayrollCost', 'View report: Payroll Cost by Branch', 'Reports'],
  ['CanViewReportPayrollPayslip', 'View report: Payslip', 'Reports'],
  ['CanViewReportPayrollCycleSummary', 'View report: Payroll Cycle Summary', 'Reports'],
  ['CanViewReportPayrollGrossToNet', 'View report: Gross to Net', 'Reports'],
  ['CanViewReportPayrollRegisterEmployee', 'View report: Payroll Register (Employee)', 'Reports'],
  ['CanViewReportPayrollRegisterBranch', 'View report: Payroll Register (Branch)', 'Reports'],
  [
    'CanViewReportPayrollRegisterDepartment',
    'View report: Payroll Register (Department)',
    'Reports',
  ],
  ['CanViewReportPayrollEarnings', 'View report: Earnings', 'Reports'],
  ['CanViewReportPayrollDeductions', 'View report: Deductions', 'Reports'],
  ['CanViewReportPayrollOvertime', 'View report: Overtime', 'Reports'],
  ['CanViewReportPayrollComparison', 'View report: Payroll Comparison', 'Reports'],
  ['CanViewReportPayrollBankSchedule', 'View report: Bank Payment Schedule', 'Reports'],
  ['CanViewReportPayrollMomoSchedule', 'View report: Mobile Money Schedule', 'Reports'],
  ['CanViewReportPayrollCashSchedule', 'View report: Cash Payment Schedule', 'Reports'],
  ['CanViewReportPayrollJournalPosting', 'View report: Payroll Journal Posting', 'Reports'],
  ['CanViewReportHrMasterList', 'View report: Employee Master List', 'Reports'],
  ['CanViewReportHrProfileSheet', 'View report: Employee Profile Sheet', 'Reports'],
  ['CanViewReportHrContactList', 'View report: Employee Contact List', 'Reports'],
  ['CanViewReportHrByDepartment', 'View report: Employee by Department', 'Reports'],
  ['CanViewReportHrByJobTitle', 'View report: Employee by Job Title', 'Reports'],
  ['CanViewReportHrByStatus', 'View report: Employee by Status', 'Reports'],
  ['CanViewReportHrNewHires', 'View report: New Hires', 'Reports'],
  ['CanViewReportHrConfirmed', 'View report: Confirmed Employees', 'Reports'],
  ['CanViewReportHrTerminated', 'View report: Terminated/Resigned', 'Reports'],
  ['CanViewReportHrHierarchy', 'View report: Manager-Subordinate', 'Reports'],
  ['CanViewReportAttendanceDaily', 'View report: Daily Attendance', 'Reports'],
  ['CanViewReportAttendanceMonthly', 'View report: Monthly Attendance', 'Reports'],
  ['CanViewReportAttendanceLate', 'View report: Late Arrivals', 'Reports'],
  ['CanViewReportAttendanceAbsence', 'View report: Absence', 'Reports'],
  ['CanViewReportAttendanceWorkedHours', 'View report: Worked Hours', 'Reports'],
  ['CanViewReportAttendanceCheckinCheckout', 'View report: Check-in/Out Details', 'Reports'],
  ['CanViewReportLeaveRequests', 'View report: Leave Requests', 'Reports'],
  ['CanViewReportLeaveStatus', 'View report: Leave Approval Status', 'Reports'],
  ['CanViewReportLeaveByEmployee', 'View report: Leave by Employee', 'Reports'],
  ['CanViewReportLeaveCalendar', 'View report: Leave Calendar', 'Reports'],
  ['CanViewReportExpensesRequests', 'View report: Expense Requests', 'Reports'],
  ['CanViewReportExpensesApproved', 'View report: Approved Expenses', 'Reports'],
  ['CanViewReportExpensesPaid', 'View report: Paid Expenses', 'Reports'],
  ['CanViewReportExpensesUnpaid', 'View report: Unpaid Expenses', 'Reports'],
  ['CanViewReportExpensesByCategory', 'View report: Expense by Category', 'Reports'],
  ['CanViewReportCashDailyConfirmation', 'View report: Cash Confirmation', 'Reports'],
  ['CanViewReportCashVariance', 'View report: Cash Variance', 'Reports'],
  ['CanViewReportCashOverage', 'View report: Cash Overage', 'Reports'],
  ['CanViewReportCashShortage', 'View report: Cash Shortage', 'Reports'],
  ['CanViewReportCustomersMasterList', 'View report: Customer Master List', 'Reports'],
  ['CanViewReportCustomersStatement', 'View report: Customer Statement', 'Reports'],
  ['CanViewReportCustomersTransactions', 'View report: Customer Transactions', 'Reports'],
  ['CanViewReportCustomersPayments', 'View report: Customer Payments', 'Reports'],
  ['CanViewReportCustomersCreditSummary', 'View report: Customer Credit Summary', 'Reports'],
  ['CanViewReportCustomersAging', 'View report: Customer Aging', 'Reports'],
  ['CanViewReportCustomersTop', 'View report: Top Customers', 'Reports'],
  ['CanViewReportCustomersInactive', 'View report: Inactive Customers', 'Reports'],
  ['CanViewReportParcelsBookings', 'View report: Booking Register', 'Reports'],
  ['CanViewReportParcelsRegister', 'View report: Parcel Register', 'Reports'],
  ['CanViewReportParcelsTracking', 'View report: Parcel Tracking', 'Reports'],
  ['CanViewReportParcelsInTransitOutgoing', 'View report: In-Transit Outgoing', 'Reports'],
  ['CanViewReportParcelsInTransitIncoming', 'View report: In-Transit Incoming', 'Reports'],
  ['CanViewReportParcelsDelivered', 'View report: Delivered Parcels', 'Reports'],
  ['CanViewReportParcelsFailed', 'View report: Undelivered Parcels', 'Reports'],
  ['CanViewReportParcelsAging', 'View report: Parcel Aging', 'Reports'],
  ['CanViewReportParcelsUncollected', 'View report: Uncollected Parcels', 'Reports'],
  ['CanViewReportConsignmentsManifest', 'View report: Consignment Manifest', 'Reports'],
  ['CanViewReportConsignmentsSummary', 'View report: Consignment Summary', 'Reports'],
  ['CanViewReportConsignmentsDispatch', 'View report: Branch Dispatch Manifest', 'Reports'],
  ['CanViewReportConsignmentsReceiving', 'View report: Branch Receiving Manifest', 'Reports'],
  ['CanViewReportTransfersInternal', 'View report: Internal Transfers', 'Reports'],
  ['CanViewReportTransfersPending', 'View report: Pending Transfers', 'Reports'],
  ['CanViewReportTransfersAcknowledged', 'View report: Acknowledged Transfers', 'Reports'],
  ['CanViewReportCashierShifts', 'View report: Shift Sessions', 'Reports'],
  ['CanViewReportCashierOpenShifts', 'View report: Open Shifts', 'Reports'],
  ['CanViewReportCashierClosedShifts', 'View report: Closed Shifts', 'Reports'],
  ['CanViewReportCashierRevenue', 'View report: Shift Revenue', 'Reports'],
  ['CanViewReportCashierSummary', 'View report: Cashier Summary', 'Reports'],
  ['CanViewReportCashierVariance', 'View report: Cashier Variance', 'Reports'],
  ['CanViewReportCashierPaymentMix', 'View report: Payment Method Mix', 'Reports'],
  ['CanViewReportInventoryStockLevels', 'View report: Inventory Stock Levels', 'Reports'],
  ['CanViewReportInventoryLowStock', 'View report: Inventory Low Stock', 'Reports'],
  ['CanViewReportInventoryMovement', 'View report: Inventory Stock Movement', 'Reports'],
  ['CanViewReportInventoryAdjustments', 'View report: Inventory Stock Adjustments', 'Reports'],
  ['CanViewReportInventoryTransfers', 'View report: Inventory Stock Transfers', 'Reports'],
  ['CanViewReportInventoryByLocation', 'View report: Inventory by Location', 'Reports'],
  ['CanViewReportInventoryProducts', 'View report: Product Master List', 'Reports'],
  ['CanViewReportAuditUser', 'View report: Audit Trail by User', 'Reports'],
  ['CanViewReportAuditModule', 'View report: Audit Trail by Module', 'Reports'],
  ['CanViewReportAuditEntity', 'View report: Audit Trail by Entity', 'Reports'],
  ['CanViewReportAuditSuspicious', 'View report: Suspicious Changes', 'Reports'],
  ['CanViewReportAuditDeleted', 'View report: Deleted Records', 'Reports'],
  ['CanViewReportAuditRoles', 'View report: User Role Permissions', 'Reports'],
  ['CanListAuditLogs', 'List audit logs', 'Audit'],
  ['CanGetAuditLog', 'Get audit log', 'Audit'],
  ['CanGetEntityAuditHistory', 'Get entity audit history', 'Audit'],
  ['CanCreateAuditExportJob', 'Create audit export job', 'Audit'],
  ['CanManageCompanyModules', 'Enable or disable company modules', 'Platform'],
  ['CanReadCompanyProfile', 'View company profile settings', 'Platform'],
  ['CanReadDashboard', 'View dashboard', 'Platform'],
  ['CanReadReportsHub', 'View reports hub', 'Reports'],
  ['CanReadCashiers', 'View cashier management pages', 'Cashiers'],
  ['CanManageAppearance', 'Manage appearance settings', 'Platform'],
  ['CanReadDepartments', 'List and view departments', 'HR'],
  ['CanCreateDepartments', 'Create departments', 'HR'],
  ['CanUpdateDepartments', 'Update departments', 'HR'],
  ['CanReadJobTitles', 'List and view job titles', 'HR'],
  ['CanCreateJobTitles', 'Create job titles', 'HR'],
  ['CanUpdateJobTitles', 'Update job titles', 'HR'],
  ['CanListEmployees', 'List employees', 'HR'],
  ['CanCreateEmployee', 'Create employee', 'HR'],
  ['CanGetEmployee', 'Get employee', 'HR'],
  ['CanUpdateEmployee', 'Update employee', 'HR'],
  ['CanCreateEmployeeUserAccount', 'Create user account from employee', 'HR'],
  ['CanCheckInAttendance', 'Check in attendance', 'HR'],
  ['CanCheckOutAttendance', 'Check out attendance', 'HR'],
  ['CanListAttendance', 'List attendance report', 'HR'],
  ['CanReadAttendance', 'View attendance pages', 'HR'],
  ['CanReadLeaveTypes', 'List leave types', 'HR'],
  ['CanCreateLeaveTypes', 'Create leave types', 'HR'],
  ['CanListLeaveRequests', 'List leave requests', 'HR'],
  ['CanReadLeaveRequests', 'View leave request pages', 'HR'],
  ['CanCreateLeaveRequest', 'Create leave request', 'HR'],
  ['CanApproveLeaveRequest', 'Approve leave request', 'HR'],
  ['CanApproveManagedLeaveRequests', 'Approve leave requests for direct reports', 'HR'],
  ['CanReadPayrollGroups', 'List payroll groups', 'Payroll'],
  ['CanCreatePayrollGroups', 'Create payroll groups', 'Payroll'],
  ['CanReadCompensation', 'View compensation setup', 'Payroll'],
  ['CanCreateCompensationType', 'Create earning and deduction types', 'Payroll'],
  ['CanUpdateCompensationType', 'Update earning and deduction types', 'Payroll'],
  ['CanSetEmployeeCompensation', 'Set employee compensation package', 'Payroll'],
  ['CanListPayrollCycles', 'List payroll cycles', 'Payroll'],
  ['CanCreatePayrollCycle', 'Create payroll cycle', 'Payroll'],
  ['CanRunPayrollCycle', 'Run payroll cycle', 'Payroll'],
  ['CanApprovePayrollCycle', 'Approve payroll cycle', 'Payroll'],
  ['CanReadPayrollInputs', 'View payroll overtime and adjustment inputs', 'Payroll'],
  ['CanCreatePayrollOvertimeEntry', 'Create payroll overtime entry', 'Payroll'],
  ['CanCreatePayrollManualAdjustment', 'Create payroll manual adjustment', 'Payroll'],
  ['CanApproveManagedPayrollInputs', 'Approve payroll inputs for direct reports', 'Payroll'],
  ['CanReadPayrollRun', 'View payroll runs', 'Payroll'],
  ['CanListPayslips', 'List payslips', 'Payroll'],
  ['CanGetPayslip', 'Get payslip', 'Payroll'],
  ['CanJournalizePayrollCycle', 'Post payroll journal entries', 'Payroll'],
  ['CanCalculateGeoDistance', 'Calculate geo distance', 'Geolocation'],
  ['CanFindNearbyBranches', 'Find nearby branches', 'Geolocation'],

  // Auth / account setup
  ['CanChangePassword', 'Change password', 'Auth'],
  ['CanResendSetupInvite', 'Resend setup invite', 'Auth'],
  ['CanReadActiveUsers', 'View active users page', 'Users'],
  ['CanReadInactiveUsers', 'View inactive users page', 'Users'],
  ['CanReadActiveCashierSessions', 'View active cashier sessions page', 'Cashiers'],
  ['CanReadCashierSessionsHistory', 'View cashier sessions history page', 'Cashiers'],
  ['CanReadOpenCashierSessions', 'View open cashier sessions page', 'Cashiers'],
  ['CanReadCloseCashierSessions', 'View close cashier sessions page', 'Cashiers'],
] as const;

type Entry = (typeof catalog)[number];
export type PermissionKey = Entry[0];

export const PermissionKeys = Object.freeze(
  Object.fromEntries(catalog.map(([key]) => [key, key])) as {
    [K in PermissionKey]: K;
  },
);

export const PermissionCatalog: ReadonlyArray<{
  key: PermissionKey;
  description: string;
  group: string;
}> = catalog.map(([key, description, group]) => ({ key, description, group }));

export const HiddenPermissionKeysInUi = new Set<PermissionKey>([]);

export const PermissionCatalogUi = PermissionCatalog.filter(
  (permission) => !HiddenPermissionKeysInUi.has(permission.key),
);

const SIDEBAR_READ_PERMISSION_PATTERN = /^Can(Read|List|Get|View)/;

export function isSidebarReadablePermission(permissionKey: string): boolean {
  return SIDEBAR_READ_PERMISSION_PATTERN.test(permissionKey);
}

export const PermissionKeySet = new Set<string>(PermissionCatalog.map((p) => p.key));

export const AccountingSetupPermissionKeys = Object.freeze({
  accounts: {
    read: PermissionKeys.CanReadAccountingAccounts,
    create: PermissionKeys.CanCreateAccountingAccounts,
    update: PermissionKeys.CanUpdateAccountingAccounts,
    delete: PermissionKeys.CanDeleteAccountingAccounts,
  },
  categories: {
    read: PermissionKeys.CanReadAccountingExpenseCategories,
    create: PermissionKeys.CanCreateAccountingExpenseCategories,
    update: PermissionKeys.CanUpdateAccountingExpenseCategories,
    delete: PermissionKeys.CanDeleteAccountingExpenseCategories,
  },
  policies: {
    read: PermissionKeys.CanReadAccountingApprovalPolicies,
    create: PermissionKeys.CanCreateAccountingApprovalPolicies,
    update: PermissionKeys.CanUpdateAccountingApprovalPolicies,
    delete: PermissionKeys.CanDeleteAccountingApprovalPolicies,
  },
  bankAccounts: {
    read: PermissionKeys.CanReadAccountingBankAccounts,
    create: PermissionKeys.CanCreateAccountingBankAccounts,
    update: PermissionKeys.CanUpdateAccountingBankAccounts,
    delete: PermissionKeys.CanDeleteAccountingBankAccounts,
  },
  taxProfiles: {
    read: PermissionKeys.CanReadAccountingTaxProfiles,
    create: PermissionKeys.CanCreateAccountingTaxProfiles,
    update: PermissionKeys.CanUpdateAccountingTaxProfiles,
    delete: PermissionKeys.CanDeleteAccountingTaxProfiles,
  },
  taxComponents: {
    read: PermissionKeys.CanReadAccountingTaxComponents,
    create: PermissionKeys.CanCreateAccountingTaxComponents,
    update: PermissionKeys.CanUpdateAccountingTaxComponents,
    delete: PermissionKeys.CanDeleteAccountingTaxComponents,
  },
});

export const RoutePermissionOverrides: Readonly<Record<string, PermissionKey>> = Object.freeze({
  '/parcels/sender-payments': PermissionKeys.CanCreateSenderPayments,
  '/parcels/processed': PermissionKeys.CanReadConsignments,
  '/parcels/pickup-queue': PermissionKeys.CanCreatePickupQueue,
  '/parcels/pickup-queue/sender': PermissionKeys.CanReadSenderPickupQueue,
  '/parcels/waiting-pickup': PermissionKeys.CanCompleteOfficePickup,
  '/parcels/pickup-queue/receiver': PermissionKeys.CanReadReceiverPickupQueue,
  '/parcels/receiver-cashier': PermissionKeys.CanCreateReceiverPayments,
  '/parcels/in-transit/outgoing': PermissionKeys.CanReadParcelOutgoing,
  '/parcels/in-transit/incoming': PermissionKeys.CanReadParcelIncoming,
  '/parcels/receive': PermissionKeys.CanReadParcelScan,
  '/parcels/home-delivery/dispatch': PermissionKeys.CanDispatchForDelivery,
  '/parcels/delivery-cashier': PermissionKeys.CanCompleteDoorstepDelivery,
  '/parcels/status': PermissionKeys.CanReadCallCenterParcelStatus,
  '/parcels/home-delivery/address': PermissionKeys.CanMarkDoorstepCalled,
  '/parcels/rider/current': PermissionKeys.CanReadRiderCurrentParcels,
  '/parcels/rider/history': PermissionKeys.CanReadRiderHistory,
  '/accounting/daily-cash': PermissionKeys.CanCreateDailyCashConfirmation,
  '/accounting/expenses': PermissionKeys.CanCreateExpenseRequest,
  '/accounting/reports': PermissionKeys.CanReadAccounting,
  '/accounting/tax': PermissionKeys.CanCreateTaxFilingPeriod,
  '/accounting/journal-entries': PermissionKeys.CanReadAccountingManualEntries,
  '/accounting/journal-approvals': PermissionKeys.CanApproveAccountingManualEntries,
  '/settings/company': PermissionKeys.CanReadCompanyProfile,
  '/settings/modules': PermissionKeys.CanManageCompanyModules,
  '/settings/appearance': PermissionKeys.CanManageAppearance,
  '/dashboard': PermissionKeys.CanReadDashboard,
  '/reports': PermissionKeys.CanReadReportsHub,
  '/cashiers': PermissionKeys.CanReadCashiers,
  '/users/active': PermissionKeys.CanReadActiveUsers,
  '/users/inactive': PermissionKeys.CanReadInactiveUsers,
  '/users/invites': PermissionKeys.CanResendSetupInvite,
  '/inventory': PermissionKeys.CanReadInventoryOverview,
  '/inventory/products': PermissionKeys.CanReadProducts,
  '/inventory/categories': PermissionKeys.CanReadProductCategories,
  '/inventory/locations': PermissionKeys.CanReadInventoryLocations,
  '/inventory/stock-levels': PermissionKeys.CanReadStockLevels,
  '/inventory/stock-movements': PermissionKeys.CanReadStockMovements,
  '/inventory/stock-adjustments': PermissionKeys.CanReadStockAdjustments,
  '/inventory/stock-transfers': PermissionKeys.CanReadStockTransfers,
  '/cashier/sessions/active': PermissionKeys.CanReadActiveCashierSessions,
  '/cashier/sessions/history': PermissionKeys.CanReadCashierSessionsHistory,
  '/cashier/sessions/open': PermissionKeys.CanReadOpenCashierSessions,
  '/cashier/sessions/close': PermissionKeys.CanReadCloseCashierSessions,
  '/hr/attendance': PermissionKeys.CanReadAttendance,
  '/hr/leave': PermissionKeys.CanReadLeaveRequests,
  '/reports/financial/trial-balance': PermissionKeys.CanViewReportFinancialTrialBalance,
  '/reports/financial/account-statement': PermissionKeys.CanViewReportFinancialAccountStatement,
  '/reports/financial/income-statement': PermissionKeys.CanViewReportFinancialIncomeStatement,
  '/reports/financial/profit-loss': PermissionKeys.CanViewReportFinancialProfitLoss,
  '/reports/financial/balance-sheet': PermissionKeys.CanViewReportFinancialBalanceSheet,
  '/reports/financial/cash-flow': PermissionKeys.CanViewReportFinancialCashFlow,
  '/reports/financial/general-ledger': PermissionKeys.CanViewReportFinancialGeneralLedger,
  '/reports/financial/journal-listing': PermissionKeys.CanViewReportFinancialJournalListing,
  '/reports/financial/account-activity': PermissionKeys.CanViewReportFinancialAccountActivity,
  '/reports/branch/monthly-summary': PermissionKeys.CanViewReportBranchMonthlySummary,
  '/reports/branch/revenue': PermissionKeys.CanViewReportBranchRevenue,
  '/reports/branch/expense': PermissionKeys.CanViewReportBranchExpense,
  '/reports/branch/profit-summary': PermissionKeys.CanViewReportBranchProfitSummary,
  '/reports/branch/payroll-cost': PermissionKeys.CanViewReportBranchPayrollCost,
  '/reports/payroll/payslip': PermissionKeys.CanViewReportPayrollPayslip,
  '/reports/payroll/cycle-summary': PermissionKeys.CanViewReportPayrollCycleSummary,
  '/reports/payroll/gross-to-net': PermissionKeys.CanViewReportPayrollGrossToNet,
  '/reports/payroll/register-employee': PermissionKeys.CanViewReportPayrollRegisterEmployee,
  '/reports/payroll/register-branch': PermissionKeys.CanViewReportPayrollRegisterBranch,
  '/reports/payroll/register-department': PermissionKeys.CanViewReportPayrollRegisterDepartment,
  '/reports/payroll/earnings': PermissionKeys.CanViewReportPayrollEarnings,
  '/reports/payroll/deductions': PermissionKeys.CanViewReportPayrollDeductions,
  '/reports/payroll/overtime': PermissionKeys.CanViewReportPayrollOvertime,
  '/reports/payroll/comparison': PermissionKeys.CanViewReportPayrollComparison,
  '/reports/payroll/bank-schedule': PermissionKeys.CanViewReportPayrollBankSchedule,
  '/reports/payroll/momo-schedule': PermissionKeys.CanViewReportPayrollMomoSchedule,
  '/reports/payroll/cash-schedule': PermissionKeys.CanViewReportPayrollCashSchedule,
  '/reports/payroll/journal-posting': PermissionKeys.CanViewReportPayrollJournalPosting,
  '/reports/hr/master-list': PermissionKeys.CanViewReportHrMasterList,
  '/reports/hr/profile-sheet': PermissionKeys.CanViewReportHrProfileSheet,
  '/reports/hr/contact-list': PermissionKeys.CanViewReportHrContactList,
  '/reports/hr/by-department': PermissionKeys.CanViewReportHrByDepartment,
  '/reports/hr/by-job-title': PermissionKeys.CanViewReportHrByJobTitle,
  '/reports/hr/by-status': PermissionKeys.CanViewReportHrByStatus,
  '/reports/hr/new-hires': PermissionKeys.CanViewReportHrNewHires,
  '/reports/hr/confirmed': PermissionKeys.CanViewReportHrConfirmed,
  '/reports/hr/terminated': PermissionKeys.CanViewReportHrTerminated,
  '/reports/hr/hierarchy': PermissionKeys.CanViewReportHrHierarchy,
  '/reports/attendance/daily': PermissionKeys.CanViewReportAttendanceDaily,
  '/reports/attendance/monthly': PermissionKeys.CanViewReportAttendanceMonthly,
  '/reports/attendance/late': PermissionKeys.CanViewReportAttendanceLate,
  '/reports/attendance/absence': PermissionKeys.CanViewReportAttendanceAbsence,
  '/reports/attendance/worked-hours': PermissionKeys.CanViewReportAttendanceWorkedHours,
  '/reports/attendance/checkin-checkout': PermissionKeys.CanViewReportAttendanceCheckinCheckout,
  '/reports/leave/requests': PermissionKeys.CanViewReportLeaveRequests,
  '/reports/leave/status': PermissionKeys.CanViewReportLeaveStatus,
  '/reports/leave/by-employee': PermissionKeys.CanViewReportLeaveByEmployee,
  '/reports/leave/calendar': PermissionKeys.CanViewReportLeaveCalendar,
  '/reports/expenses/requests': PermissionKeys.CanViewReportExpensesRequests,
  '/reports/expenses/approved': PermissionKeys.CanViewReportExpensesApproved,
  '/reports/expenses/paid': PermissionKeys.CanViewReportExpensesPaid,
  '/reports/expenses/unpaid': PermissionKeys.CanViewReportExpensesUnpaid,
  '/reports/expenses/by-category': PermissionKeys.CanViewReportExpensesByCategory,
  '/reports/cash/daily-confirmation': PermissionKeys.CanViewReportCashDailyConfirmation,
  '/reports/cash/variance': PermissionKeys.CanViewReportCashVariance,
  '/reports/cash/overage': PermissionKeys.CanViewReportCashOverage,
  '/reports/cash/shortage': PermissionKeys.CanViewReportCashShortage,
  '/reports/customers/master-list': PermissionKeys.CanViewReportCustomersMasterList,
  '/reports/customers/statement': PermissionKeys.CanViewReportCustomersStatement,
  '/reports/customers/transactions': PermissionKeys.CanViewReportCustomersTransactions,
  '/reports/customers/payments': PermissionKeys.CanViewReportCustomersPayments,
  '/reports/customers/credit-summary': PermissionKeys.CanViewReportCustomersCreditSummary,
  '/reports/customers/aging': PermissionKeys.CanViewReportCustomersAging,
  '/reports/customers/top': PermissionKeys.CanViewReportCustomersTop,
  '/reports/customers/inactive': PermissionKeys.CanViewReportCustomersInactive,
  '/reports/parcels/bookings': PermissionKeys.CanViewReportParcelsBookings,
  '/reports/parcels/register': PermissionKeys.CanViewReportParcelsRegister,
  '/reports/parcels/tracking': PermissionKeys.CanViewReportParcelsTracking,
  '/reports/parcels/in-transit-out': PermissionKeys.CanViewReportParcelsInTransitOutgoing,
  '/reports/parcels/in-transit-in': PermissionKeys.CanViewReportParcelsInTransitIncoming,
  '/reports/parcels/delivered': PermissionKeys.CanViewReportParcelsDelivered,
  '/reports/parcels/failed': PermissionKeys.CanViewReportParcelsFailed,
  '/reports/parcels/aging': PermissionKeys.CanViewReportParcelsAging,
  '/reports/parcels/uncollected': PermissionKeys.CanViewReportParcelsUncollected,
  '/reports/consignments/manifest': PermissionKeys.CanViewReportConsignmentsManifest,
  '/reports/consignments/summary': PermissionKeys.CanViewReportConsignmentsSummary,
  '/reports/consignments/dispatch': PermissionKeys.CanViewReportConsignmentsDispatch,
  '/reports/consignments/receiving': PermissionKeys.CanViewReportConsignmentsReceiving,
  '/reports/transfers/internal': PermissionKeys.CanViewReportTransfersInternal,
  '/reports/transfers/pending': PermissionKeys.CanViewReportTransfersPending,
  '/reports/transfers/acknowledged': PermissionKeys.CanViewReportTransfersAcknowledged,
  '/reports/cashier/shifts': PermissionKeys.CanViewReportCashierShifts,
  '/reports/cashier/open-shifts': PermissionKeys.CanViewReportCashierOpenShifts,
  '/reports/cashier/closed-shifts': PermissionKeys.CanViewReportCashierClosedShifts,
  '/reports/cashier/revenue': PermissionKeys.CanViewReportCashierRevenue,
  '/reports/cashier/summary': PermissionKeys.CanViewReportCashierSummary,
  '/reports/cashier/variance': PermissionKeys.CanViewReportCashierVariance,
  '/reports/cashier/payment-mix': PermissionKeys.CanViewReportCashierPaymentMix,
  '/reports/inventory/stock-levels': PermissionKeys.CanViewReportInventoryStockLevels,
  '/reports/inventory/low-stock': PermissionKeys.CanViewReportInventoryLowStock,
  '/reports/inventory/movement': PermissionKeys.CanViewReportInventoryMovement,
  '/reports/inventory/adjustments': PermissionKeys.CanViewReportInventoryAdjustments,
  '/reports/inventory/transfers': PermissionKeys.CanViewReportInventoryTransfers,
  '/reports/inventory/by-location': PermissionKeys.CanViewReportInventoryByLocation,
  '/reports/inventory/products': PermissionKeys.CanViewReportInventoryProducts,
  '/reports/audit/user': PermissionKeys.CanViewReportAuditUser,
  '/reports/audit/module': PermissionKeys.CanViewReportAuditModule,
  '/reports/audit/entity': PermissionKeys.CanViewReportAuditEntity,
  '/reports/audit/suspicious': PermissionKeys.CanViewReportAuditSuspicious,
  '/reports/audit/deleted': PermissionKeys.CanViewReportAuditDeleted,
  '/reports/audit/roles': PermissionKeys.CanViewReportAuditRoles,
});
