const catalog = [
  // RBAC / Users
  ['CanReadUsers', 'View users', 'Users'],
  ['CanCreateUsers', 'Create users', 'Users'],
  ['CanUpdateUsers', 'Update users', 'Users'],
  ['CanDeleteUsers', 'Delete users', 'Users'],
  ['CanReadRoles', 'View roles', 'RBAC'],
  ['CanCreateRoles', 'Create roles', 'RBAC'],
  ['CanUpdateRoles', 'Update roles', 'RBAC'],
  ['CanDeleteRoles', 'Delete roles', 'RBAC'],
  ['CanReadPermissions', 'View permission catalog', 'RBAC'],
  ['CanGetRolePermissions', 'Get role permissions', 'RBAC'],
  ['CanSetRolePermissions', 'Set role permissions', 'RBAC'],

  // Branches / Locations / Customers / Cards
  ['CanReadBranches', 'List and view branches', 'Branches'],
  ['CanCreateBranches', 'Create branches', 'Branches'],
  ['CanUpdateBranches', 'Update branches', 'Branches'],
  ['CanDeleteBranches', 'Delete branches', 'Branches'],
  ['CanPrintSelfServiceQrCode', 'Print branch self-service QR codes', 'Branches'],
  ['CanReadLocations', 'List and view locations', 'Locations'],
  ['CanCreateLocations', 'Create locations', 'Locations'],
  ['CanUpdateLocations', 'Update locations', 'Locations'],
  ['CanDeleteLocations', 'Delete locations', 'Locations'],
  ['CanReadWarehouses', 'List and view warehouses', 'Warehouses'],
  ['CanCreateWarehouses', 'Create warehouses', 'Warehouses'],
  ['CanUpdateWarehouses', 'Update warehouses', 'Warehouses'],
  ['CanDeleteWarehouses', 'Delete warehouses', 'Warehouses'],
  ['CanReadCustomers', 'List and view customers', 'Customers'],
  ['CanCreateCustomers', 'Create customers', 'Customers'],
  ['CanUpdateCustomers', 'Update customers', 'Customers'],
  ['CanDeleteCustomers', 'Delete customers', 'Customers'],
  ['CanReadCards', 'List and view cards', 'Cards'],
  ['CanCreateCards', 'Create cards', 'Cards'],
  ['CanUpdateCards', 'Update cards', 'Cards'],
  ['CanDeleteCards', 'Delete cards', 'Cards'],

  // Shipments / Parcels / Consignments / Grouping
  ['CanReadShipments', 'List shipments', 'Shipments'],
  ['CanCreateShipments', 'Create shipments', 'Shipments'],
  ['CanUpdateShipments', 'Update shipments', 'Shipments'],
  ['CanDeleteShipments', 'Delete shipments', 'Shipments'],
  ['CanCreateBookingWithParcels', 'Create booking with parcels', 'Shipments'],
  ['CanReadSelfServiceBookings', 'View self-service booking drafts', 'Shipments'],
  ['CanCompleteSelfServiceBookings', 'Complete self-service booking drafts', 'Shipments'],
  ['CanReadParcels', 'List and view parcels', 'Shipments'],
  ['CanReadParcelSendingModule', 'View parcel sending module', 'Shipments'],
  ['CanReadParcelReceivingModule', 'View parcel receiving module', 'Shipments'],
  ['CanReadParcelOutgoing', 'View in-transit outgoing parcels', 'Shipments'],
  ['CanReadParcelIncoming', 'View in-transit incoming parcels', 'Shipments'],
  ['CanReadParcelScan', 'View and use parcel scan-to-receive', 'Shipments'],
  ['CanCreateParcels', 'Create parcels', 'Shipments'],
  ['CanUpdateParcels', 'Update parcels', 'Shipments'],
  ['CanDeleteParcels', 'Delete parcels', 'Shipments'],
  [
    'CanSoftDeleteParcelsAndPayments',
    'Soft delete parcels and soft delete (void) linked payments with reason',
    'Shipments',
  ],
  ['CanReadParcelReconciliation', 'View parcel reconciliation cases', 'Shipments'],
  ['CanRequestParcelReconciliation', 'Request parcel reconciliation cases', 'Shipments'],
  ['CanApproveParcelReconciliation', 'Approve parcel reconciliation cases', 'Shipments'],
  ['CanExecuteParcelReconciliation', 'Execute parcel reconciliation cases', 'Shipments'],
  [
    'CanOverrideParcelReconciliationWindow',
    'Override parcel reconciliation standard execution window',
    'Shipments',
  ],
  ['CanReadConsignments', 'List and view consignments', 'Shipments'],
  ['CanCreateConsignments', 'Create consignments', 'Shipments'],
  ['CanUpdateConsignments', 'Update consignments', 'Shipments'],
  ['CanDeleteConsignments', 'Delete consignments', 'Shipments'],
  ['CanAutoGroupConsignments', 'Auto group consignments', 'Shipments'],
  ['CanReadConsignmentsHistory', 'View saved consignment history for reprinting', 'Shipments'],

  // Cashiers / Shifts
  ['CanReadCashierSessionTypes', 'List cashier session types', 'Cashiers'],
  ['CanCreateCashierSessionTypes', 'Create cashier session types', 'Cashiers'],
  ['CanReadCashierSessions', 'List and view cashier sessions', 'Cashiers'],
  ['CanOpenCashierSessions', 'Open cashier sessions', 'Cashiers'],
  ['CanReopenCashierSessions', 'Reopen cashier sessions on same day', 'Cashiers'],
  ['CanCloseCashierSessions', 'Close cashier sessions', 'Cashiers'],
  ['CanListShiftSessions', 'List shift sessions', 'Shifts'],
  ['CanOpenShiftSession', 'Open shift session', 'Shifts'],
  ['CanCloseShiftSession', 'Close shift session', 'Shifts'],
  ['CanApproveShiftSession', 'Approve shift session', 'Shifts'],
  ['CanGetActiveShiftByBranch', 'View active shift by branch', 'Shifts'],

  // Deliveries
  ['CanDispatchForDelivery', 'Dispatch parcels for delivery', 'Deliveries'],
  ['CanCreateDeliveryOrder', 'Create delivery order', 'Deliveries'],
  ['CanCreatePickupQueue', 'Create pickup queue entries', 'Deliveries'],
  ['CanReadSenderPickupQueue', 'View sender pickup queue board', 'Deliveries'],
  ['CanReadReceiverPickupQueue', 'View receiver pickup queue board', 'Deliveries'],
  ['CanReadCallCenterParcelStatus', 'View call center parcel status', 'Deliveries'],
  ['CanReadRiderCurrentParcels', 'View rider current parcels', 'Deliveries'],
  ['CanReadRiderHistory', 'View rider parcel history', 'Deliveries'],
  ['CanCompleteOfficePickup', 'Complete office pickup', 'Deliveries'],
  ['CanMarkDoorstepCalled', 'Mark doorstep called', 'Deliveries'],
  ['CanAssignDoorstepRider', 'Assign doorstep rider', 'Deliveries'],
  ['CanMarkOutForDelivery', 'Mark out for delivery', 'Deliveries'],
  ['CanCompleteDoorstepDelivery', 'Complete doorstep delivery', 'Deliveries'],
  ['CanReadParcelInternalTransfers', 'List and view parcel internal transfers', 'Deliveries'],
  ['CanCreateParcelInternalTransfers', 'Create parcel internal transfers', 'Deliveries'],
  ['CanAcknowledgeParcelInternalTransfers', 'Acknowledge parcel internal transfers', 'Deliveries'],
  ['CanCancelParcelInternalTransfers', 'Cancel parcel internal transfers', 'Deliveries'],
  ['CanReadCallCenterAssignment', 'View call center assignment page', 'Deliveries'],
  ['CanAssignCallCenterParcels', 'Assign parcels to call center representatives', 'Deliveries'],
  ['CanReadShelfPickerUpdate', 'View shelf picker update page', 'Deliveries'],
  ['CanUpdateParcelShelfPicker', 'Update parcel shelf picker assignments', 'Deliveries'],

  // Payments / Accounting
  ['CanCreatePayments', 'Create payments', 'Payments'],
  ['CanCreateSenderPayments', 'Collect sender payments', 'Payments'],
  ['CanCreateReceiverPayments', 'Collect receiver payments', 'Payments'],
  ['CanWaiveParcelStorageAccrual', 'Waive parcel storage accrual', 'Payments'],
  ['CanReadPayments', 'List and view payments', 'Payments'],
  ['CanReadAccounting', 'View accounting pages, lists, and reports', 'Accounting'],
  ['CanReadAccountingSetup', 'View accounting setup masters', 'Accounting'],
  ['CanCreateAccountingSetup', 'Create accounting setup masters', 'Accounting'],
  ['CanUpdateAccountingSetup', 'Update accounting setup masters', 'Accounting'],
  ['CanDeleteAccountingSetup', 'Delete accounting setup masters', 'Accounting'],
  ['CanReadAccountingAccounts', 'View accounting setup accounts', 'Accounting'],
  ['CanCreateAccountingAccounts', 'Create accounting setup accounts', 'Accounting'],
  ['CanUpdateAccountingAccounts', 'Update accounting setup accounts', 'Accounting'],
  ['CanDeleteAccountingAccounts', 'Delete accounting setup accounts', 'Accounting'],
  ['CanReadAccountingExpenseCategories', 'View accounting setup expense categories', 'Accounting'],
  [
    'CanCreateAccountingExpenseCategories',
    'Create accounting setup expense categories',
    'Accounting',
  ],
  [
    'CanUpdateAccountingExpenseCategories',
    'Update accounting setup expense categories',
    'Accounting',
  ],
  [
    'CanDeleteAccountingExpenseCategories',
    'Delete accounting setup expense categories',
    'Accounting',
  ],
  ['CanReadAccountingApprovalPolicies', 'View accounting setup approval policies', 'Accounting'],
  [
    'CanCreateAccountingApprovalPolicies',
    'Create accounting setup approval policies',
    'Accounting',
  ],
  [
    'CanUpdateAccountingApprovalPolicies',
    'Update accounting setup approval policies',
    'Accounting',
  ],
  [
    'CanDeleteAccountingApprovalPolicies',
    'Delete accounting setup approval policies',
    'Accounting',
  ],
  ['CanReadAccountingBankAccounts', 'View accounting setup bank accounts', 'Accounting'],
  ['CanCreateAccountingBankAccounts', 'Create accounting setup bank accounts', 'Accounting'],
  ['CanUpdateAccountingBankAccounts', 'Update accounting setup bank accounts', 'Accounting'],
  ['CanDeleteAccountingBankAccounts', 'Delete accounting setup bank accounts', 'Accounting'],
  ['CanReadAccountingTaxProfiles', 'View accounting setup tax profiles', 'Accounting'],
  ['CanCreateAccountingTaxProfiles', 'Create accounting setup tax profiles', 'Accounting'],
  ['CanUpdateAccountingTaxProfiles', 'Update accounting setup tax profiles', 'Accounting'],
  ['CanDeleteAccountingTaxProfiles', 'Delete accounting setup tax profiles', 'Accounting'],
  ['CanReadAccountingTaxComponents', 'View accounting setup tax components', 'Accounting'],
  ['CanCreateAccountingTaxComponents', 'Create accounting setup tax components', 'Accounting'],
  ['CanUpdateAccountingTaxComponents', 'Update accounting setup tax components', 'Accounting'],
  ['CanDeleteAccountingTaxComponents', 'Delete accounting setup tax components', 'Accounting'],
  ['CanCreateTaxFilingPeriod', 'Create tax filing period', 'Accounting'],
  ['CanMarkTaxFilingPeriodUnderReview', 'Mark tax filing period under review', 'Accounting'],
  ['CanSubmitTaxFilingPeriod', 'Submit tax filing period', 'Accounting'],
  ['CanCloseTaxFilingPeriod', 'Close tax filing period', 'Accounting'],
  ['CanMarkTaxItemReadyForFiling', 'Mark tax item ready for filing', 'Accounting'],
  ['CanMarkTaxItemFiled', 'Mark tax item filed', 'Accounting'],
  ['CanExcludeTaxItemFromFiling', 'Exclude tax item from filing', 'Accounting'],
  ['CanCreateDailyCashConfirmation', 'Create daily cash confirmation', 'Accounting'],
  ['CanConfirmDailyCashConfirmation', 'Confirm daily cash confirmation', 'Accounting'],
  ['CanPostDailyCashConfirmation', 'Post daily cash confirmation', 'Accounting'],
  ['CanCreateExpenseRequest', 'Create expense request', 'Accounting'],
  ['CanSubmitExpenseRequest', 'Submit expense request', 'Accounting'],
  ['CanApproveExpenseRequest', 'Approve expense request', 'Accounting'],
  ['CanRejectExpenseRequest', 'Reject expense request', 'Accounting'],
  ['CanPayExpenseRequest', 'Pay expense request', 'Accounting'],
  ['CanPostExpenseRequest', 'Post expense request', 'Accounting'],
  ['CanComputeTaxes', 'Compute taxes', 'Accounting'],
  ['CanReadAccountingManualEntries', 'View manual accounting entries page', 'Accounting'],
  ['CanCreateAccountingManualEntries', 'Create manual accounting entries', 'Accounting'],
  [
    'CanApproveAccountingManualEntries',
    'Approve and post manual accounting entries above threshold',
    'Accounting',
  ],

  // Inventory
  ['CanReadInventoryOverview', 'View inventory overview dashboard', 'Inventory'],
  ['CanReadProducts', 'View products pages', 'Inventory'],
  ['CanReadProductCategories', 'View product category pages', 'Inventory'],
  ['CanReadInventoryLocations', 'View inventory location pages', 'Inventory'],
  ['CanReadStockLevels', 'View stock levels pages', 'Inventory'],
  ['CanReadStockMovements', 'View stock movement pages', 'Inventory'],
  ['CanReadStockAdjustments', 'View stock adjustment pages', 'Inventory'],
  ['CanReadStockTransfers', 'View stock transfer pages', 'Inventory'],
  ['CanReadStockRequests', 'View stock request pages', 'Inventory'],
  ['CanReadStockMaintenanceRecords', 'View stock maintenance pages', 'Inventory'],
  ['CanListProductCategories', 'List product categories', 'Inventory'],
  ['CanGetProductCategory', 'Get product category', 'Inventory'],
  ['CanCreateProductCategory', 'Create product category', 'Inventory'],
  ['CanUpdateProductCategory', 'Update product category', 'Inventory'],
  ['CanDeleteProductCategory', 'Delete product category', 'Inventory'],
  ['CanListProducts', 'List products', 'Inventory'],
  ['CanGetProduct', 'Get product', 'Inventory'],
  ['CanCreateProduct', 'Create product', 'Inventory'],
  ['CanUpdateProduct', 'Update product', 'Inventory'],
  ['CanDeleteProduct', 'Delete product', 'Inventory'],
  ['CanListInventoryLocations', 'List inventory locations', 'Inventory'],
  ['CanGetInventoryLocation', 'Get inventory location', 'Inventory'],
  ['CanCreateInventoryLocation', 'Create inventory location', 'Inventory'],
  ['CanUpdateInventoryLocation', 'Update inventory location', 'Inventory'],
  ['CanDeleteInventoryLocation', 'Delete inventory location', 'Inventory'],
  ['CanListStockLevels', 'List stock levels', 'Inventory'],
  ['CanGetStockLevel', 'Get stock level', 'Inventory'],
  ['CanListStockMovements', 'List stock movements', 'Inventory'],
  ['CanCreateStockMovement', 'Create stock movement', 'Inventory'],
  ['CanListStockAdjustments', 'List stock adjustments', 'Inventory'],
  ['CanCreateStockAdjustment', 'Create stock adjustment', 'Inventory'],
  ['CanListStockTransfers', 'List stock transfers', 'Inventory'],
  ['CanGetStockTransfer', 'Get stock transfer', 'Inventory'],
  ['CanCreateStockTransfer', 'Create stock transfer', 'Inventory'],
  ['CanUpdateStockTransfer', 'Update stock transfer', 'Inventory'],
  ['CanListStockRequests', 'List stock requests', 'Inventory'],
  ['CanGetStockRequest', 'Get stock request', 'Inventory'],
  ['CanCreateStockRequest', 'Create stock request', 'Inventory'],
  ['CanSubmitStockRequest', 'Submit stock request', 'Inventory'],
  ['CanApproveStockRequest', 'Approve stock request', 'Inventory'],
  ['CanRejectStockRequest', 'Reject stock request', 'Inventory'],
  ['CanFulfillStockRequest', 'Fulfill stock request lines', 'Inventory'],
  ['CanGetInventoryDashboardSummary', 'View inventory dashboard summary', 'Inventory'],
  ['CanListStockMaintenanceRecords', 'List stock maintenance records', 'Inventory'],
  ['CanGetStockMaintenanceRecord', 'Get stock maintenance record', 'Inventory'],
  ['CanCreateStockMaintenanceRecord', 'Create stock maintenance record', 'Inventory'],
  ['CanResolveStockMaintenanceRecord', 'Resolve stock maintenance record', 'Inventory'],
  ['CanReadInventoryApprovalPolicies', 'View inventory approval policy pages', 'Inventory'],
  ['CanReadInventoryApprovalRequests', 'View inventory approval request pages', 'Inventory'],
  ['CanReadInventoryValuation', 'View inventory valuation pages', 'Inventory'],
  ['CanReadReplenishmentProposals', 'View inventory replenishment proposal pages', 'Inventory'],
  ['CanReadInventoryTasks', 'View inventory task pages', 'Inventory'],
  ['CanReadInventoryAuditJournal', 'View inventory audit journal pages', 'Inventory'],
  ['CanCreateInventoryCorrection', 'Create inventory corrections', 'Inventory'],
  ['CanReadInventoryEnterpriseKpis', 'View inventory enterprise KPI pages', 'Inventory'],

  // Reports / Audit / HR / Payroll / Geo
  ['CanViewReportFinancialTrialBalance', 'View report: Trial Balance', 'Reports'],
  ['CanViewReportFinancialAccountStatement', 'View report: Account Statement', 'Reports'],
  ['CanViewReportFinancialIncomeStatement', 'View report: Income Statement', 'Reports'],
  ['CanViewReportFinancialProfitLoss', 'View report: Profit & Loss', 'Reports'],
  ['CanViewReportFinancialBalanceSheet', 'View report: Balance Sheet', 'Reports'],
  ['CanViewReportFinancialCashFlow', 'View report: Cash Flow', 'Reports'],
  ['CanViewReportFinancialGeneralLedger', 'View report: General Ledger', 'Reports'],
  ['CanViewReportFinancialJournalListing', 'View report: Journal Listing', 'Reports'],
  ['CanViewReportFinancialAccountActivity', 'View report: Account Activity', 'Reports'],
  ['CanViewReportBranchMonthlySummary', 'View report: Monthly Branch Summary', 'Reports'],
  ['CanViewReportBranchRevenue', 'View report: Branch Revenue', 'Reports'],
  ['CanViewReportBranchExpense', 'View report: Branch Expense', 'Reports'],
  ['CanViewReportBranchProfitSummary', 'View report: Branch Profit Summary', 'Reports'],
  ['CanViewReportBranchPayrollCost', 'View report: Payroll Cost by Branch', 'Reports'],
  ['CanViewReportPayrollPayslip', 'View report: Payslip', 'Reports'],
  ['CanViewReportPayrollCycleSummary', 'View report: Payroll Cycle Summary', 'Reports'],
  ['CanViewReportPayrollGrossToNet', 'View report: Gross to Net', 'Reports'],
  ['CanViewReportPayrollRegisterEmployee', 'View report: Payroll Register (Employee)', 'Reports'],
  ['CanViewReportPayrollRegisterBranch', 'View report: Payroll Register (Branch)', 'Reports'],
  [
    'CanViewReportPayrollRegisterDepartment',
    'View report: Payroll Register (Department)',
    'Reports',
  ],
  ['CanViewReportPayrollEarnings', 'View report: Earnings', 'Reports'],
  ['CanViewReportPayrollDeductions', 'View report: Deductions', 'Reports'],
  ['CanViewReportPayrollOvertime', 'View report: Overtime', 'Reports'],
  ['CanViewReportPayrollComparison', 'View report: Payroll Comparison', 'Reports'],
  ['CanViewReportPayrollBankSchedule', 'View report: Bank Payment Schedule', 'Reports'],
  ['CanViewReportPayrollMomoSchedule', 'View report: Mobile Money Schedule', 'Reports'],
  ['CanViewReportPayrollCashSchedule', 'View report: Cash Payment Schedule', 'Reports'],
  ['CanViewReportPayrollJournalPosting', 'View report: Payroll Journal Posting', 'Reports'],
  ['CanViewReportHrMasterList', 'View report: Employee Master List', 'Reports'],
  ['CanViewReportHrProfileSheet', 'View report: Employee Profile Sheet', 'Reports'],
  ['CanViewReportHrContactList', 'View report: Employee Contact List', 'Reports'],
  ['CanViewReportHrByDepartment', 'View report: Employee by Department', 'Reports'],
  ['CanViewReportHrByJobTitle', 'View report: Employee by Job Title', 'Reports'],
  ['CanViewReportHrByStatus', 'View report: Employee by Status', 'Reports'],
  ['CanViewReportHrNewHires', 'View report: New Hires', 'Reports'],
  ['CanViewReportHrConfirmed', 'View report: Confirmed Employees', 'Reports'],
  ['CanViewReportHrTerminated', 'View report: Terminated/Resigned', 'Reports'],
  ['CanViewReportHrHierarchy', 'View report: Manager-Subordinate', 'Reports'],
  ['CanViewReportAttendanceDaily', 'View report: Daily Attendance', 'Reports'],
  ['CanViewReportAttendanceMonthly', 'View report: Monthly Attendance', 'Reports'],
  ['CanViewReportAttendanceLate', 'View report: Late Arrivals', 'Reports'],
  ['CanViewReportAttendanceAbsence', 'View report: Absence', 'Reports'],
  ['CanViewReportAttendanceWorkedHours', 'View report: Worked Hours', 'Reports'],
  ['CanViewReportAttendanceCheckinCheckout', 'View report: Check-in/Out Details', 'Reports'],
  ['CanViewReportLeaveRequests', 'View report: Leave Requests', 'Reports'],
  ['CanViewReportLeaveStatus', 'View report: Leave Approval Status', 'Reports'],
  ['CanViewReportLeaveByEmployee', 'View report: Leave by Employee', 'Reports'],
  ['CanViewReportLeaveCalendar', 'View report: Leave Calendar', 'Reports'],
  ['CanViewReportExpensesRequests', 'View report: Expense Requests', 'Reports'],
  ['CanViewReportExpensesApproved', 'View report: Approved Expenses', 'Reports'],
  ['CanViewReportExpensesPaid', 'View report: Paid Expenses', 'Reports'],
  ['CanViewReportExpensesUnpaid', 'View report: Unpaid Expenses', 'Reports'],
  ['CanViewReportExpensesByCategory', 'View report: Expense by Category', 'Reports'],
  ['CanViewReportCashDailyConfirmation', 'View report: Cash Confirmation', 'Reports'],
  ['CanViewReportCashVariance', 'View report: Cash Variance', 'Reports'],
  ['CanViewReportCashOverage', 'View report: Cash Overage', 'Reports'],
  ['CanViewReportCashShortage', 'View report: Cash Shortage', 'Reports'],
  ['CanViewReportCashToBePaidOutstanding', 'View report: To-Be-Paid Outstanding', 'Reports'],
  [
    'CanViewReportCashToBePaidCollectionsReconciliation',
    'View report: To-Be-Paid Collections Reconciliation',
    'Reports',
  ],
  ['CanViewReportCustomersMasterList', 'View report: Customer Master List', 'Reports'],
  ['CanViewReportCustomersStatement', 'View report: Customer Statement', 'Reports'],
  ['CanViewReportCustomersTransactions', 'View report: Customer Transactions', 'Reports'],
  ['CanViewReportCustomersPayments', 'View report: Customer Payments', 'Reports'],
  ['CanViewReportCustomersCreditSummary', 'View report: Customer Credit Summary', 'Reports'],
  ['CanViewReportCustomersAging', 'View report: Customer Aging', 'Reports'],
  ['CanViewReportCustomersTop', 'View report: Top Customers', 'Reports'],
  ['CanViewReportCustomersInactive', 'View report: Inactive Customers', 'Reports'],
  ['CanViewReportParcelsBookings', 'View report: Booking Register', 'Reports'],
  ['CanViewReportParcelsRegister', 'View report: Parcel Register', 'Reports'],
  ['CanViewReportParcelsTracking', 'View report: Parcel Tracking', 'Reports'],
  ['CanViewReportParcelsInTransitOutgoing', 'View report: In-Transit Outgoing', 'Reports'],
  ['CanViewReportParcelsInTransitIncoming', 'View report: In-Transit Incoming', 'Reports'],
  ['CanViewReportParcelsDelivered', 'View report: Delivered Parcels', 'Reports'],
  ['CanViewReportParcelsFailed', 'View report: Undelivered Parcels', 'Reports'],
  ['CanViewReportParcelsAging', 'View report: Parcel Aging', 'Reports'],
  ['CanViewReportParcelsUncollected', 'View report: Uncollected Parcels', 'Reports'],
  ['CanViewReportParcelsStatusSummary', 'View report: Parcel Status Summary', 'Reports'],
  ['CanViewReportStickerPrintUsage', 'View report: Sticker Print Usage', 'Reports'],
  ['CanViewReportParcelsDeliveryPerformance', 'View report: Delivery Performance', 'Reports'],
  ['CanViewReportConsignmentsManifest', 'View report: Consignment Manifest', 'Reports'],
  ['CanViewReportConsignmentsSummary', 'View report: Consignment Summary', 'Reports'],
  ['CanViewReportConsignmentsDispatch', 'View report: Branch Dispatch Manifest', 'Reports'],
  ['CanViewReportConsignmentsReceiving', 'View report: Branch Receiving Manifest', 'Reports'],
  ['CanViewReportTransfersInternal', 'View report: Internal Transfers', 'Reports'],
  ['CanViewReportTransfersPending', 'View report: Pending Transfers', 'Reports'],
  ['CanViewReportTransfersAcknowledged', 'View report: Acknowledged Transfers', 'Reports'],
  ['CanViewReportCashierShifts', 'View report: Shift Sessions', 'Reports'],
  ['CanViewReportCashierOpenShifts', 'View report: Open Shifts', 'Reports'],
  ['CanViewReportCashierClosedShifts', 'View report: Closed Shifts', 'Reports'],
  ['CanViewReportCashierRevenue', 'View report: Shift Revenue', 'Reports'],
  ['CanViewReportCashierSummary', 'View report: Cashier Summary', 'Reports'],
  ['CanViewReportCashierVariance', 'View report: Cashier Variance', 'Reports'],
  ['CanViewReportCashierPaymentMix', 'View report: Payment Method Mix', 'Reports'],
  ['CanViewReportInventoryStockLevels', 'View report: Inventory Stock Levels', 'Reports'],
  ['CanViewReportInventoryLowStock', 'View report: Inventory Low Stock', 'Reports'],
  ['CanViewReportInventoryMovement', 'View report: Inventory Stock Movement', 'Reports'],
  ['CanViewReportInventoryAdjustments', 'View report: Inventory Stock Adjustments', 'Reports'],
  ['CanViewReportInventoryTransfers', 'View report: Inventory Stock Transfers', 'Reports'],
  ['CanViewReportInventoryByLocation', 'View report: Inventory by Location', 'Reports'],
  ['CanViewReportInventoryProducts', 'View report: Product Master List', 'Reports'],
  ['CanViewReportAuditUser', 'View report: Audit Trail by User', 'Reports'],
  ['CanViewReportAuditModule', 'View report: Audit Trail by Module', 'Reports'],
  ['CanViewReportAuditEntity', 'View report: Audit Trail by Entity', 'Reports'],
  ['CanViewReportAuditSuspicious', 'View report: Suspicious Changes', 'Reports'],
  ['CanViewReportAuditDeleted', 'View report: Deleted Records', 'Reports'],
  ['CanViewReportAuditRoles', 'View report: User Role Permissions', 'Reports'],
  ['CanListAuditLogs', 'List audit logs', 'Audit'],
  ['CanGetAuditLog', 'Get audit log', 'Audit'],
  ['CanGetEntityAuditHistory', 'Get entity audit history', 'Audit'],
  ['CanCreateAuditExportJob', 'Create audit export job', 'Audit'],
  ['CanManageCompanyModules', 'Enable or disable company modules', 'Platform'],
  ['CanReadCompanyProfile', 'View company profile settings', 'Platform'],
  ['CanManageParcelAgeingPolicy', 'Manage parcel ageing and storage charges', 'Platform'],
  ['CanManagePrinterRouting', 'Manage desktop printer routing', 'Platform'],
  ['CanManageDesktopUpdates', 'Manage desktop app update checks and installation', 'Platform'],
  ['CanReadDashboard', 'View dashboard', 'Platform'],
  ['CanViewBasicAnalytics', 'View basic analytics', 'Analytics'],
  ['CanViewOperationalAnalytics', 'View operational analytics', 'Analytics'],
  ['CanViewFinancialAnalytics', 'View financial analytics', 'Analytics'],
  ['CanViewBranchAnalytics', 'View branch analytics', 'Analytics'],
  ['CanViewGlobalAnalytics', 'View global analytics', 'Analytics'],
  ['CanViewPersonalAnalytics', 'View personal analytics', 'Analytics'],
  ['CanReadReportsHub', 'View reports hub', 'Reports'],
  ['CanReadExecutiveInsights', 'View AI executive insights narrative', 'Reports'],
  ['CanUseAIChat', 'Use AI data insights chat', 'Reports'],
  ['CanReadOperationsExceptionsBrief', 'View AI operations exceptions brief', 'Reports'],
  ['CanReadManagementDailyBrief', 'View AI management daily brief', 'Reports'],
  ['CanReadCashiers', 'View cashier management pages', 'Cashiers'],
  ['CanManageAppearance', 'Manage appearance settings', 'Platform'],
  ['CanReadDepartments', 'List and view departments', 'HR'],
  ['CanCreateDepartments', 'Create departments', 'HR'],
  ['CanUpdateDepartments', 'Update departments', 'HR'],
  ['CanReadJobTitles', 'List and view job titles', 'HR'],
  ['CanCreateJobTitles', 'Create job titles', 'HR'],
  ['CanUpdateJobTitles', 'Update job titles', 'HR'],
  ['CanListEmployees', 'List employees', 'HR'],
  ['CanCreateEmployee', 'Create employee', 'HR'],
  ['CanGetEmployee', 'Get employee', 'HR'],
  ['CanUpdateEmployee', 'Update employee', 'HR'],
  ['CanCreateEmployeeUserAccount', 'Create user account from employee', 'HR'],
  ['CanCheckInAttendance', 'Check in attendance', 'HR'],
  ['CanCheckOutAttendance', 'Check out attendance', 'HR'],
  ['CanListAttendance', 'List attendance report', 'HR'],
  ['CanReadAttendance', 'View attendance pages', 'HR'],
  ['CanReadLeaveTypes', 'List leave types', 'HR'],
  ['CanCreateLeaveTypes', 'Create leave types', 'HR'],
  ['CanListLeaveRequests', 'List leave requests', 'HR'],
  ['CanReadLeaveRequests', 'View leave request pages', 'HR'],
  ['CanCreateLeaveRequest', 'Create leave request', 'HR'],
  ['CanViewLeaveCalendar', 'View leave calendar timeline', 'HR'],
  ['CanCreateLeaveSwapRequest', 'Create leave swap request', 'HR'],
  ['CanConfirmLeaveSwapRequest', 'Confirm leave swap request as target employee', 'HR'],
  ['CanApproveLeaveSwapRequest', 'Approve or reject leave swap requests', 'HR'],
  ['CanApproveLeaveRequest', 'Approve leave request', 'HR'],
  ['CanApproveManagedLeaveRequests', 'Approve leave requests for direct reports', 'HR'],
  ['CanReadPayrollGroups', 'List payroll groups', 'Payroll'],
  ['CanCreatePayrollGroups', 'Create payroll groups', 'Payroll'],
  ['CanReadCompensation', 'View compensation setup', 'Payroll'],
  ['CanCreateCompensationType', 'Create earning and deduction types', 'Payroll'],
  ['CanUpdateCompensationType', 'Update earning and deduction types', 'Payroll'],
  ['CanSetEmployeeCompensation', 'Set employee compensation package', 'Payroll'],
  ['CanListPayrollCycles', 'List payroll cycles', 'Payroll'],
  ['CanCreatePayrollCycle', 'Create payroll cycle', 'Payroll'],
  ['CanRunPayrollCycle', 'Run payroll cycle', 'Payroll'],
  ['CanApprovePayrollCycle', 'Approve payroll cycle', 'Payroll'],
  ['CanReadPayrollInputs', 'View payroll overtime and adjustment inputs', 'Payroll'],
  ['CanCreatePayrollOvertimeEntry', 'Create payroll overtime entry', 'Payroll'],
  ['CanCreatePayrollManualAdjustment', 'Create payroll manual adjustment', 'Payroll'],
  ['CanApproveManagedPayrollInputs', 'Approve payroll inputs for direct reports', 'Payroll'],
  ['CanReadPayrollRun', 'View payroll runs', 'Payroll'],
  ['CanListPayslips', 'List payslips', 'Payroll'],
  ['CanGetPayslip', 'Get payslip', 'Payroll'],
  ['CanJournalizePayrollCycle', 'Post payroll journal entries', 'Payroll'],
  ['CanCalculateGeoDistance', 'Calculate geo distance', 'Geolocation'],
  ['CanFindNearbyBranches', 'Find nearby branches', 'Geolocation'],
  ['CanReadProcurement', 'View procurement pages', 'Procurement'],
  ['CanCreateProcurementSuppliers', 'Create procurement suppliers', 'Procurement'],
  ['CanUpdateProcurementSuppliers', 'Update procurement suppliers', 'Procurement'],
  ['CanCreateProcurementPurchaseRequests', 'Create procurement purchase requests', 'Procurement'],
  [
    'CanApproveProcurementPurchaseRequests',
    'Approve or reject procurement purchase requests',
    'Procurement',
  ],
  ['CanReadFleetTransport', 'View fleet transport pages', 'Fleet & Transport'],
  ['CanReadFleetAnomalyBrief', 'View AI fleet anomaly brief', 'Fleet & Transport'],
  ['CanCreateFleetVehicles', 'Create fleet vehicles', 'Fleet & Transport'],
  ['CanUpdateFleetVehicles', 'Update fleet vehicles', 'Fleet & Transport'],
  ['CanReadFleetTrips', 'List and view fleet trips', 'Fleet & Transport'],
  ['CanCreateFleetTrips', 'Create fleet trips', 'Fleet & Transport'],
  ['CanAssignFleetCrew', 'Assign crew members to fleet trips', 'Fleet & Transport'],
  ['CanStartFleetTrips', 'Start fleet trips', 'Fleet & Transport'],
  ['CanCloseFleetTrips', 'Close fleet trips', 'Fleet & Transport'],
  ['CanCreateFleetFuelLogs', 'Create fleet fuel logs', 'Fleet & Transport'],
  ['CanApproveFleetFuelLogs', 'Approve or reject fleet fuel logs', 'Fleet & Transport'],

  // Fleet & Transport — granular page and action scopes
  ['CanReadFleetVehicleOptions', 'View fleet vehicle selector options', 'Fleet & Transport'],
  ['CanReadFleetVehicles', 'View fleet vehicle register', 'Fleet & Transport'],
  ['CanCreateFleetVehicle', 'Create a fleet vehicle', 'Fleet & Transport'],
  ['CanUpdateFleetVehicle', 'Update a fleet vehicle', 'Fleet & Transport'],
  [
    'CanReadFleetVehicleComplianceAlerts',
    'View fleet vehicle compliance alerts',
    'Fleet & Transport',
  ],
  ['CanReadFleetDriverOptions', 'View fleet driver selector options', 'Fleet & Transport'],
  [
    'CanReadFleetDriverComplianceAlerts',
    'View fleet driver compliance alerts',
    'Fleet & Transport',
  ],
  ['CanReadFleetComplianceDashboard', 'View fleet compliance dashboard', 'Fleet & Transport'],
  ['CanReadFleetComplianceKpis', 'View fleet compliance KPIs', 'Fleet & Transport'],
  ['CanReadFleetOpsQueue', 'View fleet operations queue', 'Fleet & Transport'],
  ['CanRunFleetAnalyticsSnapshot', 'Run fleet analytics snapshot', 'Fleet & Transport'],
  ['CanRunFleetComplianceAlerts', 'Run fleet compliance alerts', 'Fleet & Transport'],
  ['CanRunFleetComplianceEscalations', 'Run fleet compliance escalations', 'Fleet & Transport'],
  ['CanReadFleetEscalationPolicy', 'View fleet escalation policy', 'Fleet & Transport'],
  ['CanUpdateFleetEscalationPolicy', 'Update fleet escalation policy', 'Fleet & Transport'],
  ['CanReadFleetComplianceIncidents', 'View fleet compliance incidents', 'Fleet & Transport'],
  ['CanCreateFleetComplianceIncident', 'Create a fleet compliance incident', 'Fleet & Transport'],
  ['CanUpdateFleetComplianceIncident', 'Update a fleet compliance incident', 'Fleet & Transport'],
  [
    'CanTransitionFleetComplianceIncident',
    'Resolve or reopen a fleet compliance incident',
    'Fleet & Transport',
  ],
  ['CanReadFleetPolicyAcknowledgments', 'View fleet policy acknowledgments', 'Fleet & Transport'],
  [
    'CanCreateFleetPolicyAcknowledgment',
    'Create a fleet policy acknowledgment',
    'Fleet & Transport',
  ],
  [
    'CanRunFleetPolicyReminders',
    'Run fleet policy re-acknowledgment reminders',
    'Fleet & Transport',
  ],
  ['CanReadFleetDriverComplianceRecords', 'View driver compliance records', 'Fleet & Transport'],
  [
    'CanCreateFleetDriverComplianceRecord',
    'Create a driver compliance record',
    'Fleet & Transport',
  ],
  ['CanReadFleetMaintenanceDashboard', 'View fleet maintenance dashboard', 'Fleet & Transport'],
  ['CanReadFleetMaintenancePlans', 'View fleet maintenance plans', 'Fleet & Transport'],
  ['CanCreateFleetMaintenancePlan', 'Create a fleet maintenance plan', 'Fleet & Transport'],
  ['CanUpdateFleetMaintenancePlan', 'Update a fleet maintenance plan', 'Fleet & Transport'],
  ['CanReadFleetWorkOrders', 'View fleet maintenance work orders', 'Fleet & Transport'],
  ['CanCreateFleetWorkOrder', 'Create a fleet maintenance work order', 'Fleet & Transport'],
  ['CanUpdateFleetWorkOrder', 'Update a fleet maintenance work order', 'Fleet & Transport'],
  ['CanReadFleetDowntime', 'View fleet downtime events', 'Fleet & Transport'],
  ['CanCreateFleetDowntime', 'Create a fleet downtime event', 'Fleet & Transport'],
  ['CanCloseFleetDowntime', 'Close a fleet downtime event', 'Fleet & Transport'],
  ['CanReopenFleetDowntime', 'Reopen a fleet downtime event', 'Fleet & Transport'],
  ['CanReadFleetDowntimeWorkflows', 'View fleet downtime RCA workflows', 'Fleet & Transport'],
  ['CanUpdateFleetDowntimeWorkflow', 'Update a fleet downtime RCA workflow', 'Fleet & Transport'],
  ['CanReadFleetReliability', 'View fleet reliability metrics', 'Fleet & Transport'],
  ['CanReadFleetReliabilityTrends', 'View fleet reliability trends', 'Fleet & Transport'],
  ['CanReadFleetMaintenanceKpis', 'View fleet maintenance KPIs', 'Fleet & Transport'],
  ['CanReadFleetMaintenanceParts', 'View fleet maintenance parts', 'Fleet & Transport'],
  ['CanCreateFleetMaintenancePart', 'Create a fleet maintenance part', 'Fleet & Transport'],
  ['CanCreateFleetPartStockMovement', 'Create a fleet part stock movement', 'Fleet & Transport'],
  ['CanReadFleetPartStockMovements', 'View fleet part stock movements', 'Fleet & Transport'],
  ['CanReadFleetWorkOrderPartMovements', 'View work-order part movements', 'Fleet & Transport'],
  ['CanRunFleetPartsAlerts', 'Run fleet parts low-stock alerts', 'Fleet & Transport'],
  ['CanReadFleetProcurementCandidates', 'View fleet procurement candidates', 'Fleet & Transport'],
  [
    'CanReadFleetProcurementTraceability',
    'View fleet procurement traceability',
    'Fleet & Transport',
  ],
  ['CanRunFleetProcurementReorder', 'Run fleet procurement reorder', 'Fleet & Transport'],
  ['CanRunFleetMaintenanceAutomation', 'Run fleet maintenance automation', 'Fleet & Transport'],
  [
    'CanRunFleetAutomationOrchestration',
    'Run unified fleet automation orchestration',
    'Fleet & Transport',
  ],
  ['CanReadFleetVehicle', 'View a fleet vehicle', 'Fleet & Transport'],
  ['CanUpdateFleetVehicleLifecycle', 'Update fleet vehicle lifecycle', 'Fleet & Transport'],
  [
    'CanRunFleetVehicleLifecycleAutomation',
    'Run fleet vehicle lifecycle automation',
    'Fleet & Transport',
  ],
  ['CanReadFleetVehicleDocuments', 'View fleet vehicle documents', 'Fleet & Transport'],
  ['CanCreateFleetVehicleDocument', 'Create a fleet vehicle document', 'Fleet & Transport'],
  ['CanReadFleetRoutePlans', 'View fleet route plans', 'Fleet & Transport'],
  ['CanCreateFleetRoutePlan', 'Create a fleet route plan', 'Fleet & Transport'],
  ['CanReadFleetRoutePlan', 'View a fleet route plan', 'Fleet & Transport'],
  ['CanReadFleetTripsPage', 'View fleet trips', 'Fleet & Transport'],
  ['CanCreateFleetTrip', 'Create a fleet trip', 'Fleet & Transport'],
  ['CanStartFleetTrip', 'Start a fleet trip', 'Fleet & Transport'],
  ['CanCloseFleetTrip', 'Close a fleet trip', 'Fleet & Transport'],
  ['CanAssignFleetTripRoute', 'Assign a route to a fleet trip', 'Fleet & Transport'],
  ['CanReadFleetTrip', 'View a fleet trip', 'Fleet & Transport'],
  ['CanReadFleetTripCrew', 'View fleet trip crew', 'Fleet & Transport'],
  ['CanAssignFleetTripCrew', 'Assign fleet trip crew', 'Fleet & Transport'],
  ['CanReadFleetTripEvents', 'View fleet trip events', 'Fleet & Transport'],
  ['CanReadFleetTripLoads', 'View fleet trip loads', 'Fleet & Transport'],
  ['CanAssignFleetTripLoad', 'Assign a load to a fleet trip', 'Fleet & Transport'],
  ['CanUpdateFleetTripLoadMatch', 'Update a fleet trip load match', 'Fleet & Transport'],
  ['CanReadFleetTripTelemetry', 'View fleet trip telemetry', 'Fleet & Transport'],
  ['CanRecordFleetTripTelemetry', 'Record fleet trip telemetry', 'Fleet & Transport'],
  ['CanReadFleetTripStatusUpdates', 'View fleet trip status updates', 'Fleet & Transport'],
  ['CanRecordFleetTripStatusUpdate', 'Record a fleet trip status update', 'Fleet & Transport'],
  ['CanReadFleetTripTimeline', 'View a fleet trip timeline', 'Fleet & Transport'],
  ['CanCheckInFleetTrip', 'Check in a fleet trip', 'Fleet & Transport'],
  ['CanCheckOutFleetTrip', 'Check out a fleet trip', 'Fleet & Transport'],
  ['CanReadFleetRosters', 'View fleet shift rosters', 'Fleet & Transport'],
  ['CanReadFleetRoster', 'View a fleet shift roster', 'Fleet & Transport'],
  ['CanCreateFleetRoster', 'Create a fleet shift roster', 'Fleet & Transport'],
  ['CanUpdateFleetRoster', 'Update a fleet shift roster', 'Fleet & Transport'],
  ['CanReadFleetFuelAnalytics', 'View fleet fuel analytics', 'Fleet & Transport'],
  ['CanReadFleetFuelFraudSignals', 'View fleet fuel fraud signals', 'Fleet & Transport'],
  ['CanReadFleetFuelLogs', 'View fleet fuel logs', 'Fleet & Transport'],
  ['CanReadFleetFuelApprovals', 'View fleet fuel approvals', 'Fleet & Transport'],
  ['CanCreateFleetFuelLog', 'Create a fleet fuel log', 'Fleet & Transport'],
  ['CanApproveFleetFuelLog', 'Approve a fleet fuel log', 'Fleet & Transport'],
  ['CanRejectFleetFuelLog', 'Reject a fleet fuel log', 'Fleet & Transport'],
  ['CanReadFleetDispatchBoard', 'View fleet dispatch board', 'Fleet & Transport'],
  ['CanReadFleetDispatchPerformance', 'View fleet dispatch performance', 'Fleet & Transport'],
  ['CanReadFleetDispatchExceptions', 'View fleet dispatch exceptions', 'Fleet & Transport'],
  ['CanReadFleetDispatchRouteQueue', 'View fleet route assignment queue', 'Fleet & Transport'],
  ['CanReadFleetDispatchLoadCandidates', 'View fleet load candidates', 'Fleet & Transport'],
  ['CanReadFleetDecisionSupport', 'View fleet decision support', 'Fleet & Transport'],
  ['CanReadFleetExecutiveScorecard', 'View fleet executive scorecard', 'Fleet & Transport'],
  ['CanReadFleetUnitEconomics', 'View fleet unit economics', 'Fleet & Transport'],
  [
    'CanReadCustomerWalletCredit',
    'View customer wallet and credit control pages',
    'Customer Wallet',
  ],
  [
    'CanCreateCustomerWalletCreditPayments',
    'Create customer wallet and credit payments',
    'Customer Wallet',
  ],
  [
    'CanApproveCustomerWalletCreditControls',
    'Approve customer wallet credit block and unblock controls',
    'Customer Wallet',
  ],
  ['CanReadReconciliation', 'View reconciliation pages', 'Reconciliation'],
  ['CanCreateReconciliationSessions', 'Create reconciliation sessions', 'Reconciliation'],
  [
    'CanApproveReconciliationSessions',
    'Approve and finalize reconciliation sessions',
    'Reconciliation',
  ],
  [
    'CanCreateReconciliationBankSettlements',
    'Create bank settlement reconciliation records',
    'Reconciliation',
  ],
  [
    'CanApproveReconciliationBankSettlements',
    'Approve or reject bank settlement reconciliation records',
    'Reconciliation',
  ],
  ['CanReadNotificationHub', 'View notification hub pages', 'Notification Hub'],
  [
    'CanManageNotificationProviders',
    'Create and update notification providers',
    'Notification Hub',
  ],
  [
    'CanManageNotificationTemplates',
    'Create and update notification templates',
    'Notification Hub',
  ],
  [
    'CanCreateNotificationCampaigns',
    'Create and submit notification campaigns',
    'Notification Hub',
  ],
  [
    'CanApproveNotificationCampaigns',
    'Approve or reject notification campaigns',
    'Notification Hub',
  ],
  ['CanSendNotificationCampaigns', 'Send approved notification campaigns', 'Notification Hub'],
  ['CanRetryNotificationMessages', 'Retry failed notification messages', 'Notification Hub'],
  [
    'CanSendCallCenterNotifications',
    'Send parcel call-center SMS and email notifications',
    'Notification Hub',
  ],
  ['CanReadItSupportTickets', 'View IT support tickets', 'IT Support'],
  ['CanCreateItSupportTickets', 'Create IT support tickets', 'IT Support'],
  ['CanUpdateItSupportTickets', 'Update IT support tickets', 'IT Support'],
  ['CanReopenItSupportTickets', 'Reopen closed IT support tickets', 'IT Support'],

  // Auth / account setup
  ['CanChangePassword', 'Change password', 'Auth'],
  ['CanSetUserPassword', 'Set another user password', 'Auth'],
  ['CanResendSetupInvite', 'Resend setup invite', 'Auth'],
  ['CanReadActiveUsers', 'View active users page', 'Users'],
  ['CanReadInactiveUsers', 'View inactive users page', 'Users'],
  ['CanReadActiveCashierSessions', 'View active cashier sessions page', 'Cashiers'],
  ['CanReadCashierSessionsHistory', 'View cashier sessions history page', 'Cashiers'],
  ['CanReadOpenCashierSessions', 'View open cashier sessions page', 'Cashiers'],
  ['CanReadCloseCashierSessions', 'View close cashier sessions page', 'Cashiers'],
] as const;

type Entry = (typeof catalog)[number];
export type PermissionKey = Entry[0];

export const PermissionKeys = Object.freeze(
  Object.fromEntries(catalog.map(([key]) => [key, key])) as {
    [K in PermissionKey]: K;
  },
);

export const PermissionCatalog: ReadonlyArray<{
  key: PermissionKey;
  description: string;
  group: string;
}> = catalog.map(([key, description, group]) => ({ key, description, group }));

export const HiddenPermissionKeysInUi = new Set<PermissionKey>([PermissionKeys.CanSetUserPassword]);

export const PermissionCatalogUi = PermissionCatalog.filter(
  (permission) => !HiddenPermissionKeysInUi.has(permission.key),
);

export const ReportPermissionKeys = PermissionCatalog.filter(
  (permission) =>
    permission.group === 'Reports' &&
    (permission.key === PermissionKeys.CanReadReportsHub ||
      permission.key.startsWith('CanViewReport')),
).map((permission) => permission.key);

export const PermissionKeySet = new Set<string>(PermissionCatalog.map((p) => p.key));

const LegacyPermissionKeyAliases: Readonly<Record<string, readonly PermissionKey[]>> = {
  CanGetCashierPerformanceReport: [PermissionKeys.CanViewReportCashierShifts],
  CanGetShiftRevenueReport: [PermissionKeys.CanViewReportCashierRevenue],
  CanGetBranchProfitabilityReport: [PermissionKeys.CanViewReportBranchProfitSummary],
  CanGetCreditExposureReport: [
    PermissionKeys.CanViewReportCustomersCreditSummary,
    PermissionKeys.CanViewReportCustomersAging,
  ],
  CanGetOutstandingToBePaidReport: [
    PermissionKeys.CanViewReportCashToBePaidOutstanding,
    PermissionKeys.CanViewReportCashToBePaidCollectionsReconciliation,
  ],
  CanGetParcelStatusSummaryReport: [
    PermissionKeys.CanViewReportParcelsStatusSummary,
    PermissionKeys.CanViewReportParcelsDeliveryPerformance,
  ],
  CanGetLowStockReport: [PermissionKeys.CanViewReportInventoryLowStock],
  CanGetMovementHistory: [PermissionKeys.CanViewReportInventoryMovement],
  CanGetShiftReport: [PermissionKeys.CanViewReportCashierShifts],
};

export function normalizePermissionKeys(permissionKeys: readonly string[]): PermissionKey[] {
  const normalized = new Set<PermissionKey>();

  for (const permissionKey of permissionKeys) {
    if (PermissionKeySet.has(permissionKey)) {
      normalized.add(permissionKey as PermissionKey);
      continue;
    }

    for (const replacementKey of LegacyPermissionKeyAliases[permissionKey] ?? []) {
      normalized.add(replacementKey);
    }
  }

  return [...normalized];
}

const SIDEBAR_READ_PERMISSION_PATTERN = /^Can(Read|List|Get|View)/;

export function isSidebarReadablePermission(permissionKey: string): boolean {
  return SIDEBAR_READ_PERMISSION_PATTERN.test(permissionKey);
}

export const AccountingSetupPermissionKeys = Object.freeze({
  accounts: {
    read: PermissionKeys.CanReadAccountingAccounts,
    create: PermissionKeys.CanCreateAccountingAccounts,
    update: PermissionKeys.CanUpdateAccountingAccounts,
    delete: PermissionKeys.CanDeleteAccountingAccounts,
  },
  categories: {
    read: PermissionKeys.CanReadAccountingExpenseCategories,
    create: PermissionKeys.CanCreateAccountingExpenseCategories,
    update: PermissionKeys.CanUpdateAccountingExpenseCategories,
    delete: PermissionKeys.CanDeleteAccountingExpenseCategories,
  },
  policies: {
    read: PermissionKeys.CanReadAccountingApprovalPolicies,
    create: PermissionKeys.CanCreateAccountingApprovalPolicies,
    update: PermissionKeys.CanUpdateAccountingApprovalPolicies,
    delete: PermissionKeys.CanDeleteAccountingApprovalPolicies,
  },
  bankAccounts: {
    read: PermissionKeys.CanReadAccountingBankAccounts,
    create: PermissionKeys.CanCreateAccountingBankAccounts,
    update: PermissionKeys.CanUpdateAccountingBankAccounts,
    delete: PermissionKeys.CanDeleteAccountingBankAccounts,
  },
  taxProfiles: {
    read: PermissionKeys.CanReadAccountingTaxProfiles,
    create: PermissionKeys.CanCreateAccountingTaxProfiles,
    update: PermissionKeys.CanUpdateAccountingTaxProfiles,
    delete: PermissionKeys.CanDeleteAccountingTaxProfiles,
  },
  taxComponents: {
    read: PermissionKeys.CanReadAccountingTaxComponents,
    create: PermissionKeys.CanCreateAccountingTaxComponents,
    update: PermissionKeys.CanUpdateAccountingTaxComponents,
    delete: PermissionKeys.CanDeleteAccountingTaxComponents,
  },
});

export const RoutePermissionOverrides: Readonly<Record<string, PermissionKey>> = Object.freeze({
  '/users/password-management': PermissionKeys.CanSetUserPassword,
  '/parcels/sender-payments': PermissionKeys.CanCreateSenderPayments,
  '/parcels/processed': PermissionKeys.CanReadConsignments,
  '/parcels/consignments/history': PermissionKeys.CanReadConsignmentsHistory,
  '/parcels/pickup-queue': PermissionKeys.CanCreatePickupQueue,
  '/parcels/pickup-queue/sender': PermissionKeys.CanReadSenderPickupQueue,
  '/parcels/waiting-pickup': PermissionKeys.CanCompleteOfficePickup,
  '/parcels/pickup-queue/receiver': PermissionKeys.CanReadReceiverPickupQueue,
  '/parcels/receiver-cashier': PermissionKeys.CanCreateReceiverPayments,
  '/parcels/uncollected': PermissionKeys.CanViewReportParcelsUncollected,
  '/parcels/in-transit/outgoing': PermissionKeys.CanReadParcelOutgoing,
  '/parcels/in-transit/incoming': PermissionKeys.CanReadParcelIncoming,
  '/parcels/discrepancies': PermissionKeys.CanReadParcelIncoming,
  '/parcels/reconciliation-cases': PermissionKeys.CanReadParcelReconciliation,
  '/parcels/receive': PermissionKeys.CanReadParcelScan,
  '/parcels/home-delivery/dispatch': PermissionKeys.CanDispatchForDelivery,
  '/parcels/home-delivery/rider-assigned': PermissionKeys.CanDispatchForDelivery,
  '/parcels/delivery-cashier': PermissionKeys.CanCompleteDoorstepDelivery,
  '/parcels/status': PermissionKeys.CanReadCallCenterParcelStatus,
  '/parcels/call-center-assignment': PermissionKeys.CanReadCallCenterAssignment,
  '/parcels/shelf-picker-update': PermissionKeys.CanReadShelfPickerUpdate,
  '/parcels/home-delivery/address': PermissionKeys.CanMarkDoorstepCalled,
  '/parcels/rider/current': PermissionKeys.CanReadRiderCurrentParcels,
  '/parcels/rider/history': PermissionKeys.CanReadRiderHistory,
  '/parcels/edit/:id': PermissionKeys.CanCreateBookingWithParcels,
  '/parcels/self-service': PermissionKeys.CanReadSelfServiceBookings,
  '/parcels/self-service/:id': PermissionKeys.CanCompleteSelfServiceBookings,
  '/accounting/daily-cash': PermissionKeys.CanCreateDailyCashConfirmation,
  '/accounting/daily-cash/drafts': PermissionKeys.CanConfirmDailyCashConfirmation,
  '/accounting/daily-cash/approvals': PermissionKeys.CanConfirmDailyCashConfirmation,
  '/accounting/daily-cash/recorded': PermissionKeys.CanPostDailyCashConfirmation,
  '/accounting/expenses': PermissionKeys.CanCreateExpenseRequest,
  '/accounting/expenses/drafts': PermissionKeys.CanSubmitExpenseRequest,
  '/accounting/expenses/approvals': PermissionKeys.CanApproveExpenseRequest,
  '/accounting/expenses/payments': PermissionKeys.CanPayExpenseRequest,
  '/accounting/expenses/posting': PermissionKeys.CanPostExpenseRequest,
  '/accounting/expenses/history': PermissionKeys.CanReadAccounting,
  '/accounting/reports': PermissionKeys.CanReadAccounting,
  '/accounting/tax': PermissionKeys.CanCreateTaxFilingPeriod,
  '/accounting/journal-entries': PermissionKeys.CanReadAccountingManualEntries,
  '/accounting/journal-approvals': PermissionKeys.CanApproveAccountingManualEntries,
  '/procurement': PermissionKeys.CanReadProcurement,
  '/procurement/suppliers': PermissionKeys.CanReadProcurement,
  '/procurement/suppliers/new': PermissionKeys.CanCreateProcurementSuppliers,
  '/procurement/suppliers/edit/:id': PermissionKeys.CanUpdateProcurementSuppliers,
  '/procurement/demands': PermissionKeys.CanReadProcurement,
  '/procurement/demands/new': PermissionKeys.CanCreateProcurementPurchaseRequests,
  '/procurement/demands/fleet-low-stock': PermissionKeys.CanCreateProcurementPurchaseRequests,
  '/procurement/demands/inventory-low-stock': PermissionKeys.CanCreateProcurementPurchaseRequests,
  '/procurement/demands/consolidations': PermissionKeys.CanReadProcurement,
  '/procurement/demands/consolidations/new': PermissionKeys.CanCreateProcurementPurchaseRequests,
  '/procurement/demands/approvals': PermissionKeys.CanApproveProcurementPurchaseRequests,
  '/procurement/fleet-policies': PermissionKeys.CanReadProcurement,
  '/procurement/fleet-policies/new': PermissionKeys.CanCreateProcurementPurchaseRequests,
  '/procurement/fleet-policies/edit/:id': PermissionKeys.CanCreateProcurementPurchaseRequests,
  '/procurement/supplier-quotes': PermissionKeys.CanReadProcurement,
  '/procurement/supplier-quotes/new': PermissionKeys.CanCreateProcurementPurchaseRequests,
  '/procurement/purchase-orders': PermissionKeys.CanReadProcurement,
  '/procurement/purchase-orders/new': PermissionKeys.CanCreateProcurementPurchaseRequests,
  '/procurement/goods-receipts': PermissionKeys.CanReadProcurement,
  '/procurement/goods-receipts/new': PermissionKeys.CanCreateProcurementPurchaseRequests,
  '/procurement/purchase-requests': PermissionKeys.CanReadProcurement,
  '/procurement/purchase-requests/new': PermissionKeys.CanCreateProcurementPurchaseRequests,
  '/procurement/purchase-requests/edit/:id': PermissionKeys.CanCreateProcurementPurchaseRequests,
  '/procurement/purchase-requests/approvals': PermissionKeys.CanApproveProcurementPurchaseRequests,
  '/fleet-transport': PermissionKeys.CanReadFleetTransport,
  '/fleet-transport/vehicles': PermissionKeys.CanReadFleetVehicles,
  '/fleet-transport/vehicles/new': PermissionKeys.CanCreateFleetVehicle,
  '/fleet-transport/vehicles/edit/:id': PermissionKeys.CanUpdateFleetVehicle,
  '/fleet-transport/trips': PermissionKeys.CanReadFleetTripsPage,
  '/fleet-transport/trips/new': PermissionKeys.CanCreateFleetTrip,
  '/fleet-transport/routes/plans': PermissionKeys.CanReadFleetRoutePlans,
  '/fleet-transport/routes/plans/new': PermissionKeys.CanCreateFleetRoutePlan,
  '/fleet-transport/trips/view/:id': PermissionKeys.CanReadFleetTrip,
  '/fleet-transport/trips/:id': PermissionKeys.CanReadFleetTrip,
  '/fleet-transport/trips/crew/:id': PermissionKeys.CanAssignFleetTripCrew,
  '/fleet-transport/trips/start/:id': PermissionKeys.CanStartFleetTrip,
  '/fleet-transport/trips/close/:id': PermissionKeys.CanCloseFleetTrip,
  '/fleet-transport/vehicles/view/:id': PermissionKeys.CanReadFleetVehicle,
  '/fleet-transport/vehicles/view/:id/documents': PermissionKeys.CanReadFleetVehicleDocuments,
  '/fleet-transport/vehicles/view/:id/documents/new': PermissionKeys.CanCreateFleetVehicleDocument,
  '/fleet-transport/fuel-logs': PermissionKeys.CanReadFleetFuelLogs,
  '/fleet-transport/fuel-analytics': PermissionKeys.CanReadFleetFuelAnalytics,
  '/fleet-transport/fuel-analytics/fraud-signals': PermissionKeys.CanReadFleetFuelFraudSignals,
  '/fleet-transport/fuel-logs/new': PermissionKeys.CanCreateFleetFuelLog,
  '/fleet-transport/fuel-logs/edit/:id': PermissionKeys.CanCreateFleetFuelLog,
  '/fleet-transport/fuel-logs/approvals': PermissionKeys.CanReadFleetFuelApprovals,
  '/fleet-transport/drivers/compliance': PermissionKeys.CanReadFleetDriverComplianceRecords,
  '/fleet-transport/drivers/compliance/new': PermissionKeys.CanCreateFleetDriverComplianceRecord,
  '/fleet-transport/drivers/training': PermissionKeys.CanReadFleetDriverOptions,
  '/fleet-transport/drivers/training/new': PermissionKeys.CanCreateFleetDriverComplianceRecord,
  '/fleet-transport/drivers/incidents/history': PermissionKeys.CanReadFleetComplianceIncidents,
  '/fleet-transport/drivers/rosters/history': PermissionKeys.CanReadFleetRosters,
  '/fleet-transport/rosters': PermissionKeys.CanReadFleetRosters,
  '/fleet-transport/rosters/new': PermissionKeys.CanCreateFleetRoster,
  '/fleet-transport/rosters/edit/:id': PermissionKeys.CanUpdateFleetRoster,
  '/fleet-transport/compliance': PermissionKeys.CanReadFleetComplianceDashboard,
  '/fleet-transport/compliance/kpis': PermissionKeys.CanReadFleetComplianceKpis,
  '/fleet-transport/compliance/ops': PermissionKeys.CanReadFleetOpsQueue,
  '/fleet-transport/compliance/escalation-policy': PermissionKeys.CanReadFleetEscalationPolicy,
  '/fleet-transport/compliance/ops/incidents/new': PermissionKeys.CanCreateFleetComplianceIncident,
  '/fleet-transport/compliance/ops/policy-acks/new':
    PermissionKeys.CanCreateFleetPolicyAcknowledgment,
  '/fleet-transport/maintenance': PermissionKeys.CanReadFleetMaintenanceDashboard,
  '/fleet-transport/maintenance/plans/new': PermissionKeys.CanCreateFleetMaintenancePlan,
  '/fleet-transport/maintenance/work-orders': PermissionKeys.CanReadFleetWorkOrders,
  '/fleet-transport/maintenance/work-orders/new': PermissionKeys.CanCreateFleetWorkOrder,
  '/fleet-transport/maintenance/downtime': PermissionKeys.CanReadFleetDowntime,
  '/fleet-transport/maintenance/downtime/new': PermissionKeys.CanCreateFleetDowntime,
  '/fleet-transport/maintenance/parts/new': PermissionKeys.CanCreateFleetMaintenancePart,
  '/fleet-transport/maintenance/parts/movements': PermissionKeys.CanReadFleetPartStockMovements,
  '/fleet-transport/maintenance/parts/movements/new':
    PermissionKeys.CanCreateFleetPartStockMovement,
  '/fleet-transport/maintenance/procurement-linkage':
    PermissionKeys.CanReadFleetProcurementCandidates,
  '/fleet-transport/dispatch/board': PermissionKeys.CanReadFleetDispatchBoard,
  '/fleet-transport/dispatch/route-assignments': PermissionKeys.CanReadFleetDispatchRouteQueue,
  '/fleet-transport/dispatch/load-matching': PermissionKeys.CanReadFleetDispatchLoadCandidates,
  '/fleet-transport/dispatch/load-matching/new': PermissionKeys.CanAssignFleetTripLoad,
  '/fleet-transport/dispatch/check-in': PermissionKeys.CanCheckInFleetTrip,
  '/fleet-transport/dispatch/check-out': PermissionKeys.CanCheckOutFleetTrip,
  '/fleet-transport/dispatch/exception-queue': PermissionKeys.CanReadFleetDispatchExceptions,
  '/fleet-transport/decision-support': PermissionKeys.CanReadFleetDecisionSupport,
  '/fleet-transport/decision-support/executive-scorecard':
    PermissionKeys.CanReadFleetExecutiveScorecard,
  '/fleet-transport/decision-support/unit-economics': PermissionKeys.CanReadFleetUnitEconomics,
  '/customer-wallet-credit': PermissionKeys.CanReadCustomerWalletCredit,
  '/customer-wallet-credit/accounts': PermissionKeys.CanReadCustomerWalletCredit,
  '/customer-wallet-credit/payments/new': PermissionKeys.CanCreateCustomerWalletCreditPayments,
  '/customer-wallet-credit/payments/edit/:id': PermissionKeys.CanCreateCustomerWalletCreditPayments,
  '/customer-wallet-credit/approvals': PermissionKeys.CanApproveCustomerWalletCreditControls,
  '/reconciliation': PermissionKeys.CanReadReconciliation,
  '/reconciliation/sessions': PermissionKeys.CanReadReconciliation,
  '/reconciliation/sessions/new': PermissionKeys.CanCreateReconciliationSessions,
  '/reconciliation/sessions/edit/:id': PermissionKeys.CanCreateReconciliationSessions,
  '/reconciliation/sessions/approvals': PermissionKeys.CanApproveReconciliationSessions,
  '/reconciliation/bank-settlements': PermissionKeys.CanReadReconciliation,
  '/reconciliation/bank-settlements/new': PermissionKeys.CanCreateReconciliationBankSettlements,
  '/reconciliation/bank-settlements/edit/:id':
    PermissionKeys.CanCreateReconciliationBankSettlements,
  '/reconciliation/bank-settlements/approvals':
    PermissionKeys.CanApproveReconciliationBankSettlements,
  '/notification-hub': PermissionKeys.CanReadNotificationHub,
  '/notification-hub/providers': PermissionKeys.CanReadNotificationHub,
  '/notification-hub/providers/new': PermissionKeys.CanManageNotificationProviders,
  '/notification-hub/templates': PermissionKeys.CanReadNotificationHub,
  '/notification-hub/templates/new': PermissionKeys.CanManageNotificationTemplates,
  '/notification-hub/campaigns': PermissionKeys.CanReadNotificationHub,
  '/notification-hub/campaigns/new': PermissionKeys.CanCreateNotificationCampaigns,
  '/notification-hub/campaigns/edit/:id': PermissionKeys.CanCreateNotificationCampaigns,
  '/notification-hub/campaigns/approvals': PermissionKeys.CanApproveNotificationCampaigns,
  '/notification-hub/dispatches': PermissionKeys.CanReadNotificationHub,
  '/it-support/tickets': PermissionKeys.CanReadItSupportTickets,
  '/it-support/tickets/new': PermissionKeys.CanCreateItSupportTickets,
  '/settings/company': PermissionKeys.CanReadCompanyProfile,
  '/settings/sms': PermissionKeys.CanReadCompanyProfile,
  '/settings/modules': PermissionKeys.CanManageCompanyModules,
  '/settings/parcel-ageing': PermissionKeys.CanManageParcelAgeingPolicy,
  '/settings/app-updates': PermissionKeys.CanManageDesktopUpdates,
  '/settings/printer-routing': PermissionKeys.CanManagePrinterRouting,
  '/settings/appearance': PermissionKeys.CanManageAppearance,
  '/dashboard': PermissionKeys.CanReadDashboard,
  '/dashboard/accountant': PermissionKeys.CanReadDashboard,
  '/dashboard/admin': PermissionKeys.CanReadDashboard,
  '/dashboard/auditor': PermissionKeys.CanReadDashboard,
  '/dashboard/cashier': PermissionKeys.CanReadDashboard,
  '/dashboard/ceo': PermissionKeys.CanReadDashboard,
  '/dashboard/hr-manager': PermissionKeys.CanReadDashboard,
  '/dashboard/it': PermissionKeys.CanReadDashboard,
  '/dashboard/secretary': PermissionKeys.CanReadDashboard,
  '/bi-executive-dashboard': PermissionKeys.CanReadReportsHub,
  '/ai-chat': PermissionKeys.CanUseAIChat,
  '/analytics': PermissionKeys.CanReadDashboard,
  '/reports': PermissionKeys.CanReadReportsHub,
  '/cashiers': PermissionKeys.CanReadCashiers,
  '/users/active': PermissionKeys.CanReadActiveUsers,
  '/users/inactive': PermissionKeys.CanReadInactiveUsers,
  '/users/invites': PermissionKeys.CanResendSetupInvite,
  '/inventory': PermissionKeys.CanReadInventoryOverview,
  '/inventory/products': PermissionKeys.CanReadProducts,
  '/inventory/categories': PermissionKeys.CanReadProductCategories,
  '/inventory/locations': PermissionKeys.CanReadInventoryLocations,
  '/inventory/stock-levels': PermissionKeys.CanReadStockLevels,
  '/inventory/stock-lots': PermissionKeys.CanReadStockLevels,
  '/inventory/stock-lots/new': PermissionKeys.CanCreateStockMovement,
  '/inventory/stock-lots/view/:id': PermissionKeys.CanReadStockLevels,
  '/inventory/stock-lots/traceability/:id': PermissionKeys.CanReadStockLevels,
  '/inventory/stock-lots/analytics': PermissionKeys.CanReadStockLevels,
  '/inventory/stock-lots/expiry-alerts': PermissionKeys.CanReadStockLevels,
  '/inventory/stock-movements': PermissionKeys.CanReadStockMovements,
  '/inventory/stock-movements/edit/:id': PermissionKeys.CanCreateStockMovement,
  '/inventory/stock-consumption': PermissionKeys.CanReadStockMovements,
  '/inventory/stock-adjustments': PermissionKeys.CanReadStockAdjustments,
  '/inventory/stock-adjustments/edit/:id': PermissionKeys.CanCreateStockAdjustment,
  '/inventory/stock-transfers': PermissionKeys.CanReadStockTransfers,
  '/inventory/stock-transfers/receive/:id': PermissionKeys.CanUpdateStockTransfer,
  '/inventory/stock-requests': PermissionKeys.CanReadStockRequests,
  '/inventory/stock-requests/issue': PermissionKeys.CanReadStockRequests,
  '/inventory/stock-requests/receive': PermissionKeys.CanReadStockRequests,
  '/inventory/stock-requests/new': PermissionKeys.CanCreateStockRequest,
  '/inventory/stock-requests/view/:id': PermissionKeys.CanGetStockRequest,
  '/inventory/stock-requests/fulfill/:requestId/:lineId': PermissionKeys.CanFulfillStockRequest,
  '/inventory/stock-requests/acknowledge/:requestId/:lineId': PermissionKeys.CanFulfillStockRequest,
  '/inventory/stock-count-sessions': PermissionKeys.CanReadStockLevels,
  '/inventory/stock-count-sessions/new': PermissionKeys.CanCreateStockMovement,
  '/inventory/stock-count-sessions/view/:id': PermissionKeys.CanReadStockLevels,
  '/inventory/stock-reservations': PermissionKeys.CanReadStockRequests,
  '/inventory/stock-reservations/view/:id': PermissionKeys.CanGetStockRequest,
  '/inventory/stock-reservations/exceptions': PermissionKeys.CanReadStockRequests,
  '/inventory/stock-allocation-policy': PermissionKeys.CanApproveStockRequest,
  '/inventory/stock-allocation-policy/edit': PermissionKeys.CanApproveStockRequest,
  '/inventory/monitoring': PermissionKeys.CanReadInventoryOverview,
  '/inventory/reorder-suggestions': PermissionKeys.CanReadInventoryOverview,
  '/inventory/stock-maintenance': PermissionKeys.CanReadStockMaintenanceRecords,
  '/inventory/stock-maintenance/new': PermissionKeys.CanCreateStockMaintenanceRecord,
  '/inventory/stock-maintenance/view/:id': PermissionKeys.CanGetStockMaintenanceRecord,
  '/inventory/approval-policies': PermissionKeys.CanReadInventoryApprovalPolicies,
  '/inventory/approval-policies/new': PermissionKeys.CanReadInventoryApprovalPolicies,
  '/inventory/approval-requests': PermissionKeys.CanReadInventoryApprovalRequests,
  '/inventory/valuation': PermissionKeys.CanReadInventoryValuation,
  '/inventory/replenishment-proposals': PermissionKeys.CanReadReplenishmentProposals,
  '/inventory/replenishment-proposals/new': PermissionKeys.CanReadReplenishmentProposals,
  '/inventory/replenishment-proposals/view/:id': PermissionKeys.CanReadReplenishmentProposals,
  '/inventory/tasks': PermissionKeys.CanReadInventoryTasks,
  '/inventory/tasks/new': PermissionKeys.CanReadInventoryTasks,
  '/inventory/tasks/view/:id': PermissionKeys.CanReadInventoryTasks,
  '/inventory/audit/journal': PermissionKeys.CanReadInventoryAuditJournal,
  '/inventory/audit/corrections/new': PermissionKeys.CanCreateInventoryCorrection,
  '/inventory/reports/enterprise-kpis': PermissionKeys.CanReadInventoryEnterpriseKpis,
  '/cashier/sessions/active': PermissionKeys.CanReadActiveCashierSessions,
  '/cashier/sessions/history': PermissionKeys.CanReadCashierSessionsHistory,
  '/cashier/sessions/open': PermissionKeys.CanReadOpenCashierSessions,
  '/cashier/sessions/close': PermissionKeys.CanReadCloseCashierSessions,
  '/hr/attendance': PermissionKeys.CanReadAttendance,
  '/hr/leave': PermissionKeys.CanReadLeaveRequests,
  '/hr/leave/requests': PermissionKeys.CanReadLeaveRequests,
  '/hr/leave/history': PermissionKeys.CanReadLeaveRequests,
  '/hr/leave/types': PermissionKeys.CanReadLeaveTypes,
  '/reports/financial/trial-balance': PermissionKeys.CanViewReportFinancialTrialBalance,
  '/reports/financial/account-statement': PermissionKeys.CanViewReportFinancialAccountStatement,
  '/reports/financial/income-statement': PermissionKeys.CanViewReportFinancialIncomeStatement,
  '/reports/financial/profit-loss': PermissionKeys.CanViewReportFinancialProfitLoss,
  '/reports/financial/balance-sheet': PermissionKeys.CanViewReportFinancialBalanceSheet,
  '/reports/financial/cash-flow': PermissionKeys.CanViewReportFinancialCashFlow,
  '/reports/financial/general-ledger': PermissionKeys.CanViewReportFinancialGeneralLedger,
  '/reports/financial/journal-listing': PermissionKeys.CanViewReportFinancialJournalListing,
  '/reports/financial/account-activity': PermissionKeys.CanViewReportFinancialAccountActivity,
  '/reports/branch/monthly-summary': PermissionKeys.CanViewReportBranchMonthlySummary,
  '/reports/branch/revenue': PermissionKeys.CanViewReportBranchRevenue,
  '/reports/branch/expense': PermissionKeys.CanViewReportBranchExpense,
  '/reports/branch/profit-summary': PermissionKeys.CanViewReportBranchProfitSummary,
  '/reports/branch/payroll-cost': PermissionKeys.CanViewReportBranchPayrollCost,
  '/reports/payroll/payslip': PermissionKeys.CanViewReportPayrollPayslip,
  '/reports/payroll/cycle-summary': PermissionKeys.CanViewReportPayrollCycleSummary,
  '/reports/payroll/gross-to-net': PermissionKeys.CanViewReportPayrollGrossToNet,
  '/reports/payroll/register-employee': PermissionKeys.CanViewReportPayrollRegisterEmployee,
  '/reports/payroll/register-branch': PermissionKeys.CanViewReportPayrollRegisterBranch,
  '/reports/payroll/register-department': PermissionKeys.CanViewReportPayrollRegisterDepartment,
  '/reports/payroll/earnings': PermissionKeys.CanViewReportPayrollEarnings,
  '/reports/payroll/deductions': PermissionKeys.CanViewReportPayrollDeductions,
  '/reports/payroll/overtime': PermissionKeys.CanViewReportPayrollOvertime,
  '/reports/payroll/comparison': PermissionKeys.CanViewReportPayrollComparison,
  '/reports/payroll/bank-schedule': PermissionKeys.CanViewReportPayrollBankSchedule,
  '/reports/payroll/momo-schedule': PermissionKeys.CanViewReportPayrollMomoSchedule,
  '/reports/payroll/cash-schedule': PermissionKeys.CanViewReportPayrollCashSchedule,
  '/reports/payroll/journal-posting': PermissionKeys.CanViewReportPayrollJournalPosting,
  '/reports/hr/master-list': PermissionKeys.CanViewReportHrMasterList,
  '/reports/hr/profile-sheet': PermissionKeys.CanViewReportHrProfileSheet,
  '/reports/hr/contact-list': PermissionKeys.CanViewReportHrContactList,
  '/reports/hr/by-department': PermissionKeys.CanViewReportHrByDepartment,
  '/reports/hr/by-job-title': PermissionKeys.CanViewReportHrByJobTitle,
  '/reports/hr/by-status': PermissionKeys.CanViewReportHrByStatus,
  '/reports/hr/new-hires': PermissionKeys.CanViewReportHrNewHires,
  '/reports/hr/confirmed': PermissionKeys.CanViewReportHrConfirmed,
  '/reports/hr/terminated': PermissionKeys.CanViewReportHrTerminated,
  '/reports/hr/hierarchy': PermissionKeys.CanViewReportHrHierarchy,
  '/reports/attendance/daily': PermissionKeys.CanViewReportAttendanceDaily,
  '/reports/attendance/monthly': PermissionKeys.CanViewReportAttendanceMonthly,
  '/reports/attendance/late': PermissionKeys.CanViewReportAttendanceLate,
  '/reports/attendance/absence': PermissionKeys.CanViewReportAttendanceAbsence,
  '/reports/attendance/worked-hours': PermissionKeys.CanViewReportAttendanceWorkedHours,
  '/reports/attendance/checkin-checkout': PermissionKeys.CanViewReportAttendanceCheckinCheckout,
  '/reports/leave/requests': PermissionKeys.CanViewReportLeaveRequests,
  '/reports/leave/status': PermissionKeys.CanViewReportLeaveStatus,
  '/reports/leave/by-employee': PermissionKeys.CanViewReportLeaveByEmployee,
  '/reports/leave/calendar': PermissionKeys.CanViewReportLeaveCalendar,
  '/reports/expenses/requests': PermissionKeys.CanViewReportExpensesRequests,
  '/reports/expenses/approved': PermissionKeys.CanViewReportExpensesApproved,
  '/reports/expenses/paid': PermissionKeys.CanViewReportExpensesPaid,
  '/reports/expenses/unpaid': PermissionKeys.CanViewReportExpensesUnpaid,
  '/reports/expenses/by-category': PermissionKeys.CanViewReportExpensesByCategory,
  '/reports/cash/daily-confirmation': PermissionKeys.CanViewReportCashDailyConfirmation,
  '/reports/cash/variance': PermissionKeys.CanViewReportCashVariance,
  '/reports/cash/overage': PermissionKeys.CanViewReportCashOverage,
  '/reports/cash/shortage': PermissionKeys.CanViewReportCashShortage,
  '/reports/customers/master-list': PermissionKeys.CanViewReportCustomersMasterList,
  '/reports/customers/statement': PermissionKeys.CanViewReportCustomersStatement,
  '/reports/customers/transactions': PermissionKeys.CanViewReportCustomersTransactions,
  '/reports/customers/payments': PermissionKeys.CanViewReportCustomersPayments,
  '/reports/customers/credit-summary': PermissionKeys.CanViewReportCustomersCreditSummary,
  '/reports/customers/aging': PermissionKeys.CanViewReportCustomersAging,
  '/reports/customers/top': PermissionKeys.CanViewReportCustomersTop,
  '/reports/customers/inactive': PermissionKeys.CanViewReportCustomersInactive,
  '/reports/parcels/bookings': PermissionKeys.CanViewReportParcelsBookings,
  '/reports/parcels/register': PermissionKeys.CanViewReportParcelsRegister,
  '/reports/parcels/tracking': PermissionKeys.CanViewReportParcelsTracking,
  '/reports/parcels/in-transit-out': PermissionKeys.CanViewReportParcelsInTransitOutgoing,
  '/reports/parcels/in-transit-in': PermissionKeys.CanViewReportParcelsInTransitIncoming,
  '/reports/parcels/delivered': PermissionKeys.CanViewReportParcelsDelivered,
  '/reports/parcels/failed': PermissionKeys.CanViewReportParcelsFailed,
  '/reports/parcels/aging': PermissionKeys.CanViewReportParcelsAging,
  '/reports/parcels/uncollected': PermissionKeys.CanViewReportParcelsUncollected,
  '/reports/consignments/manifest': PermissionKeys.CanViewReportConsignmentsManifest,
  '/reports/consignments/summary': PermissionKeys.CanViewReportConsignmentsSummary,
  '/reports/consignments/dispatch': PermissionKeys.CanViewReportConsignmentsDispatch,
  '/reports/consignments/receiving': PermissionKeys.CanViewReportConsignmentsReceiving,
  '/reports/transfers/internal': PermissionKeys.CanViewReportTransfersInternal,
  '/reports/transfers/pending': PermissionKeys.CanViewReportTransfersPending,
  '/reports/transfers/acknowledged': PermissionKeys.CanViewReportTransfersAcknowledged,
  '/reports/cashier/shifts': PermissionKeys.CanViewReportCashierShifts,
  '/reports/cashier/open-shifts': PermissionKeys.CanViewReportCashierOpenShifts,
  '/reports/cashier/closed-shifts': PermissionKeys.CanViewReportCashierClosedShifts,
  '/reports/cashier/revenue': PermissionKeys.CanViewReportCashierRevenue,
  '/reports/cashier/summary': PermissionKeys.CanViewReportCashierSummary,
  '/reports/cashier/variance': PermissionKeys.CanViewReportCashierVariance,
  '/reports/cashier/payment-mix': PermissionKeys.CanViewReportCashierPaymentMix,
  '/reports/inventory/stock-levels': PermissionKeys.CanViewReportInventoryStockLevels,
  '/reports/inventory/low-stock': PermissionKeys.CanViewReportInventoryLowStock,
  '/reports/inventory/movement': PermissionKeys.CanViewReportInventoryMovement,
  '/reports/inventory/adjustments': PermissionKeys.CanViewReportInventoryAdjustments,
  '/reports/inventory/transfers': PermissionKeys.CanViewReportInventoryTransfers,
  '/reports/inventory/by-location': PermissionKeys.CanViewReportInventoryByLocation,
  '/reports/inventory/products': PermissionKeys.CanViewReportInventoryProducts,
  '/reports/audit/user': PermissionKeys.CanViewReportAuditUser,
  '/reports/audit/module': PermissionKeys.CanViewReportAuditModule,
  '/reports/audit/entity': PermissionKeys.CanViewReportAuditEntity,
  '/reports/audit/suspicious': PermissionKeys.CanViewReportAuditSuspicious,
  '/reports/audit/deleted': PermissionKeys.CanViewReportAuditDeleted,
  '/reports/audit/roles': PermissionKeys.CanViewReportAuditRoles,
});
