const catalog = [
  // RBAC / Users
  ['CanReadUsers', 'View users', 'Users'],
  ['CanCreateUsers', 'Create users', 'Users'],
  ['CanUpdateUsers', 'Update users', 'Users'],
  ['CanDeleteUsers', 'Delete users', 'Users'],
  ['CanReadRoles', 'View roles', 'RBAC'],
  ['CanCreateRoles', 'Create roles', 'RBAC'],
  ['CanUpdateRoles', 'Update roles', 'RBAC'],
  ['CanDeleteRoles', 'Delete roles', 'RBAC'],
  ['CanManageRolePermissions', 'Manage role permissions', 'RBAC'],
  ['CanReadPermissions', 'View permission catalog', 'RBAC'],
  ['CanGetRolePermissions', 'Get role permissions', 'RBAC'],
  ['CanSetRolePermissions', 'Set role permissions', 'RBAC'],

  // Branches / Locations / Statuses / Customers / Cards
  ['CanReadBranches', 'List and view branches', 'Branches'],
  ['CanCreateBranches', 'Create branches', 'Branches'],
  ['CanUpdateBranches', 'Update branches', 'Branches'],
  ['CanDeleteBranches', 'Delete branches', 'Branches'],
  ['CanReadLocations', 'List and view locations', 'Locations'],
  ['CanCreateLocations', 'Create locations', 'Locations'],
  ['CanUpdateLocations', 'Update locations', 'Locations'],
  ['CanDeleteLocations', 'Delete locations', 'Locations'],
  ['CanReadWarehouses', 'List and view warehouses', 'Warehouses'],
  ['CanCreateWarehouses', 'Create warehouses', 'Warehouses'],
  ['CanUpdateWarehouses', 'Update warehouses', 'Warehouses'],
  ['CanDeleteWarehouses', 'Delete warehouses', 'Warehouses'],
  ['CanReadStatuses', 'List and view statuses', 'Statuses'],
  ['CanCreateStatuses', 'Create statuses', 'Statuses'],
  ['CanUpdateStatuses', 'Update statuses', 'Statuses'],
  ['CanDeleteStatuses', 'Delete statuses', 'Statuses'],
  ['CanReadCustomers', 'List and view customers', 'Customers'],
  ['CanCreateCustomers', 'Create customers', 'Customers'],
  ['CanUpdateCustomers', 'Update customers', 'Customers'],
  ['CanDeleteCustomers', 'Delete customers', 'Customers'],
  ['CanReadCards', 'List and view cards', 'Cards'],
  ['CanCreateCards', 'Create cards', 'Cards'],
  ['CanUpdateCards', 'Update cards', 'Cards'],
  ['CanDeleteCards', 'Delete cards', 'Cards'],

  // Shipments / Parcels / Consignments / Grouping
  ['CanReadShipments', 'List shipments', 'Shipments'],
  ['CanCreateShipments', 'Create shipments', 'Shipments'],
  ['CanUpdateShipments', 'Update shipments', 'Shipments'],
  ['CanDeleteShipments', 'Delete shipments', 'Shipments'],
  ['CanCreateBookingWithParcels', 'Create booking with parcels', 'Shipments'],
  ['CanReadParcels', 'List and view parcels', 'Shipments'],
  ['CanCreateParcels', 'Create parcels', 'Shipments'],
  ['CanUpdateParcels', 'Update parcels', 'Shipments'],
  ['CanDeleteParcels', 'Delete parcels', 'Shipments'],
  ['CanReadConsignments', 'List and view consignments', 'Shipments'],
  ['CanCreateConsignments', 'Create consignments', 'Shipments'],
  ['CanUpdateConsignments', 'Update consignments', 'Shipments'],
  ['CanDeleteConsignments', 'Delete consignments', 'Shipments'],
  ['CanAutoGroupConsignments', 'Auto group consignments', 'Shipments'],

  // Cashiers / Shifts
  ['CanReadCashierSessionTypes', 'List cashier session types', 'Cashiers'],
  ['CanCreateCashierSessionTypes', 'Create cashier session types', 'Cashiers'],
  ['CanReadCashierSessions', 'List and view cashier sessions', 'Cashiers'],
  ['CanOpenCashierSessions', 'Open cashier sessions', 'Cashiers'],
  ['CanReopenCashierSessions', 'Reopen cashier sessions on same day', 'Cashiers'],
  ['CanCloseCashierSessions', 'Close cashier sessions', 'Cashiers'],
  ['CanListShiftSessions', 'List shift sessions', 'Shifts'],
  ['CanOpenShiftSession', 'Open shift session', 'Shifts'],
  ['CanCloseShiftSession', 'Close shift session', 'Shifts'],
  ['CanApproveShiftSession', 'Approve shift session', 'Shifts'],
  ['CanGetShiftReport', 'View shift report', 'Shifts'],
  ['CanGetActiveShiftByBranch', 'View active shift by branch', 'Shifts'],

  // Deliveries
  ['CanCreateDeliveryOrder', 'Create delivery order', 'Deliveries'],
  ['CanCompleteOfficePickup', 'Complete office pickup', 'Deliveries'],
  ['CanMarkDoorstepCalled', 'Mark doorstep called', 'Deliveries'],
  ['CanAssignDoorstepRider', 'Assign doorstep rider', 'Deliveries'],
  ['CanMarkOutForDelivery', 'Mark out for delivery', 'Deliveries'],
  ['CanCompleteDoorstepDelivery', 'Complete doorstep delivery', 'Deliveries'],
  ['CanReadParcelInternalTransfers', 'List and view parcel internal transfers', 'Deliveries'],
  ['CanCreateParcelInternalTransfers', 'Create parcel internal transfers', 'Deliveries'],
  ['CanAcknowledgeParcelInternalTransfers', 'Acknowledge parcel internal transfers', 'Deliveries'],
  ['CanCancelParcelInternalTransfers', 'Cancel parcel internal transfers', 'Deliveries'],

  // Payments / Accounting
  ['CanCreatePayments', 'Create payments', 'Payments'],
  ['CanReadPayments', 'List and view payments', 'Payments'],
  ['CanReadAccounting', 'View accounting pages, lists, and reports', 'Accounting'],
  ['CanManageAccountingSetup', 'Manage accounting setup masters', 'Accounting'],
  ['CanManageTaxFiling', 'Manage tax filing periods and tax filing actions', 'Accounting'],
  ['CanPostAccountingEntries', 'Create, approve, pay, and post accounting entries', 'Accounting'],
  ['CanComputeTaxes', 'Compute taxes', 'Accounting'],

  // Inventory
  ['CanListProductCategories', 'List product categories', 'Inventory'],
  ['CanGetProductCategory', 'Get product category', 'Inventory'],
  ['CanCreateProductCategory', 'Create product category', 'Inventory'],
  ['CanUpdateProductCategory', 'Update product category', 'Inventory'],
  ['CanDeleteProductCategory', 'Delete product category', 'Inventory'],
  ['CanListProducts', 'List products', 'Inventory'],
  ['CanGetProduct', 'Get product', 'Inventory'],
  ['CanCreateProduct', 'Create product', 'Inventory'],
  ['CanUpdateProduct', 'Update product', 'Inventory'],
  ['CanDeleteProduct', 'Delete product', 'Inventory'],
  ['CanListInventoryLocations', 'List inventory locations', 'Inventory'],
  ['CanGetInventoryLocation', 'Get inventory location', 'Inventory'],
  ['CanCreateInventoryLocation', 'Create inventory location', 'Inventory'],
  ['CanUpdateInventoryLocation', 'Update inventory location', 'Inventory'],
  ['CanDeleteInventoryLocation', 'Delete inventory location', 'Inventory'],
  ['CanListStockLevels', 'List stock levels', 'Inventory'],
  ['CanGetStockLevel', 'Get stock level', 'Inventory'],
  ['CanListStockMovements', 'List stock movements', 'Inventory'],
  ['CanCreateStockMovement', 'Create stock movement', 'Inventory'],
  ['CanListStockAdjustments', 'List stock adjustments', 'Inventory'],
  ['CanCreateStockAdjustment', 'Create stock adjustment', 'Inventory'],
  ['CanListStockTransfers', 'List stock transfers', 'Inventory'],
  ['CanGetStockTransfer', 'Get stock transfer', 'Inventory'],
  ['CanCreateStockTransfer', 'Create stock transfer', 'Inventory'],
  ['CanUpdateStockTransfer', 'Update stock transfer', 'Inventory'],
  ['CanGetLowStockReport', 'View low stock report', 'Inventory'],
  ['CanGetMovementHistory', 'View movement history report', 'Inventory'],

  // Reports / Audit / HR / Payroll / Geo
  ['CanGetCashierPerformanceReport', 'View cashier performance report', 'Reports'],
  ['CanGetShiftRevenueReport', 'View shift revenue report', 'Reports'],
  ['CanGetBranchProfitabilityReport', 'View branch profitability report', 'Reports'],
  ['CanGetCreditExposureReport', 'View credit exposure report', 'Reports'],
  ['CanGetOutstandingToBePaidReport', 'View outstanding to-be-paid report', 'Reports'],
  ['CanGetParcelStatusSummaryReport', 'View parcel status summary report', 'Reports'],
  ['CanListAuditLogs', 'List audit logs', 'Audit'],
  ['CanGetAuditLog', 'Get audit log', 'Audit'],
  ['CanGetEntityAuditHistory', 'Get entity audit history', 'Audit'],
  ['CanCreateAuditExportJob', 'Create audit export job', 'Audit'],
  ['CanManageCompanyModules', 'Enable or disable company modules', 'Platform'],
  ['CanReadDepartments', 'List and view departments', 'HR'],
  ['CanCreateDepartments', 'Create departments', 'HR'],
  ['CanUpdateDepartments', 'Update departments', 'HR'],
  ['CanReadJobTitles', 'List and view job titles', 'HR'],
  ['CanCreateJobTitles', 'Create job titles', 'HR'],
  ['CanUpdateJobTitles', 'Update job titles', 'HR'],
  ['CanListEmployees', 'List employees', 'HR'],
  ['CanCreateEmployee', 'Create employee', 'HR'],
  ['CanGetEmployee', 'Get employee', 'HR'],
  ['CanUpdateEmployee', 'Update employee', 'HR'],
  ['CanCreateEmployeeUserAccount', 'Create user account from employee', 'HR'],
  ['CanCheckInAttendance', 'Check in attendance', 'HR'],
  ['CanCheckOutAttendance', 'Check out attendance', 'HR'],
  ['CanListAttendance', 'List attendance report', 'HR'],
  ['CanReadLeaveTypes', 'List leave types', 'HR'],
  ['CanCreateLeaveTypes', 'Create leave types', 'HR'],
  ['CanListLeaveRequests', 'List leave requests', 'HR'],
  ['CanCreateLeaveRequest', 'Create leave request', 'HR'],
  ['CanApproveLeaveRequest', 'Approve leave request', 'HR'],
  ['CanApproveManagedLeaveRequests', 'Approve leave requests for direct reports', 'HR'],
  ['CanReadPayrollGroups', 'List payroll groups', 'Payroll'],
  ['CanCreatePayrollGroups', 'Create payroll groups', 'Payroll'],
  ['CanReadCompensation', 'View compensation setup', 'Payroll'],
  ['CanManageCompensation', 'Manage compensation setup', 'Payroll'],
  ['CanListPayrollCycles', 'List payroll cycles', 'Payroll'],
  ['CanCreatePayrollCycle', 'Create payroll cycle', 'Payroll'],
  ['CanRunPayrollCycle', 'Run payroll cycle', 'Payroll'],
  ['CanApprovePayrollCycle', 'Approve payroll cycle', 'Payroll'],
  ['CanReadPayrollInputs', 'View payroll overtime and adjustment inputs', 'Payroll'],
  ['CanManagePayrollInputs', 'Manage payroll overtime and adjustment inputs', 'Payroll'],
  ['CanApproveManagedPayrollInputs', 'Approve payroll inputs for direct reports', 'Payroll'],
  ['CanReadPayrollRun', 'View payroll runs', 'Payroll'],
  ['CanListPayslips', 'List payslips', 'Payroll'],
  ['CanGetPayslip', 'Get payslip', 'Payroll'],
  ['CanJournalizePayrollCycle', 'Post payroll journal entries', 'Payroll'],
  ['CanCalculateGeoDistance', 'Calculate geo distance', 'Geolocation'],
  ['CanFindNearbyBranches', 'Find nearby branches', 'Geolocation'],

  // Auth / account setup
  ['CanChangePassword', 'Change password', 'Auth'],
  ['CanResendSetupInvite', 'Resend setup invite', 'Auth'],
  ['CanValidateResetPasswordToken', 'Validate reset token', 'Auth'],
  ['CanResetPasswordWithToken', 'Reset password with token', 'Auth'],
] as const;

type Entry = (typeof catalog)[number];
export type PermissionKey = Entry[0];

export const PermissionKeys = Object.freeze(
  Object.fromEntries(catalog.map(([key]) => [key, key])) as {
    [K in PermissionKey]: K;
  },
);

export const PermissionCatalog: ReadonlyArray<{
  key: PermissionKey;
  description: string;
  group: string;
}> = catalog.map(([key, description, group]) => ({ key, description, group }));

export const PermissionKeySet = new Set<string>(PermissionCatalog.map((p) => p.key));
