import type { PermissionKey } from './constants';
import type { GroupDefault } from './ui-metadata-types';
export { resolveModule, resolveSubdomain } from './ui-metadata-resolvers';

export const GROUP_DEFAULTS: Record<string, GroupDefault> = {
  Users: { domain: 'Technology', subdomain: 'Identity & Access', module: 'User Administration' },
  RBAC: {
    domain: 'Governance',
    subdomain: 'Access Governance',
    module: 'Role & Permission Governance',
  },
  Branches: {
    domain: 'Operations',
    subdomain: 'Order Fulfillment',
    module: 'Branch Network Management',
  },
  Locations: {
    domain: 'Operations',
    subdomain: 'Order Fulfillment',
    module: 'Location Master Management',
  },
  Warehouses: {
    domain: 'Supply Chain',
    subdomain: 'Network & Facilities',
    module: 'Warehouse Management',
  },
  Customers: {
    domain: 'Commercial',
    subdomain: 'Customer Lifecycle',
    module: 'Customer Master Management',
  },
  Cards: {
    domain: 'Commercial',
    subdomain: 'Customer Lifecycle',
    module: 'Customer Identification',
  },
  Shipments: { domain: 'Operations', subdomain: 'Parcel Lifecycle', module: 'Booking & Shipping' },
  Cashiers: {
    domain: 'Finance',
    subdomain: 'Cash Operations',
    module: 'Cashier Session Management',
  },
  Shifts: { domain: 'Finance', subdomain: 'Cash Operations', module: 'Shift Session Management' },
  Deliveries: {
    domain: 'Operations',
    subdomain: 'Delivery Execution',
    module: 'Last Mile Delivery',
  },
  Payments: {
    domain: 'Finance',
    subdomain: 'Receivables & Collections',
    module: 'Payment Collection',
  },
  Accounting: {
    domain: 'Finance',
    subdomain: 'Financial Accounting',
    module: 'General Ledger & Controls',
  },
  Inventory: {
    domain: 'Supply Chain',
    subdomain: 'Inventory Management',
    module: 'Inventory Control',
  },
  Procurement: {
    domain: 'Supply Chain',
    subdomain: 'Procurement',
    module: 'Sourcing & Purchasing',
  },
  'Fleet & Transport': {
    domain: 'Operations',
    subdomain: 'Routing & Dispatch',
    module: 'Fleet Transport Operations',
  },
  'Customer Wallet': {
    domain: 'Finance',
    subdomain: 'Credit & Wallet Management',
    module: 'Customer Wallet & Credit Control',
  },
  Reconciliation: {
    domain: 'Finance',
    subdomain: 'Reconciliation',
    module: 'Operational Reconciliation',
  },
  'Notification Hub': {
    domain: 'Commercial',
    subdomain: 'Customer Engagement',
    module: 'Notification Orchestration',
  },
  Reports: { domain: 'Insights', subdomain: 'Enterprise Reporting', module: 'Enterprise Reports' },
  Analytics: {
    domain: 'Insights',
    subdomain: 'Business Analytics',
    module: 'Business Analytics',
  },
  Audit: { domain: 'Governance', subdomain: 'Audit & Compliance', module: 'Audit Trail' },
  Platform: {
    domain: 'Technology',
    subdomain: 'Platform Administration',
    module: 'Platform Configuration',
  },
  HR: {
    domain: 'Human Capital',
    subdomain: 'Workforce Administration',
    module: 'Employee Administration',
  },
  Payroll: {
    domain: 'Human Capital',
    subdomain: 'Compensation & Payroll',
    module: 'Payroll Operations',
  },
  'IT Support': {
    domain: 'Technology',
    subdomain: 'Service Operations',
    module: 'IT Support Desk',
  },
  Geolocation: {
    domain: 'Operations',
    subdomain: 'Call Center Operations',
    module: 'Geolocation Services',
  },
  Auth: {
    domain: 'Technology',
    subdomain: 'Identity & Access',
    module: 'Authentication & Credential Security',
  },
};

export const KEY_OVERRIDES: Partial<Record<PermissionKey, Partial<GroupDefault>>> = {
  CanReadConsignments: { module: 'Consignment Processing' },
  CanCreateConsignments: { module: 'Consignment Processing' },
  CanUpdateConsignments: { module: 'Consignment Processing' },
  CanDeleteConsignments: { module: 'Consignment Processing' },
  CanAutoGroupConsignments: { module: 'Consignment Processing' },
  CanReadParcelReceivingModule: { module: 'Parcel Receiving' },
  CanReadParcelIncoming: { module: 'Parcel Receiving' },
  CanReadParcelScan: { module: 'Parcel Receiving' },
  CanCreateReceiverPayments: {
    domain: 'Operations',
    subdomain: 'Parcel Lifecycle',
    module: 'Parcel Receiving',
  },
  CanCreateSenderPayments: {
    domain: 'Operations',
    subdomain: 'Parcel Lifecycle',
    module: 'Booking & Shipping',
  },
  CanReadParcelReconciliation: { module: 'Parcel Reconciliation' },
  CanRequestParcelReconciliation: { module: 'Parcel Reconciliation' },
  CanApproveParcelReconciliation: { module: 'Parcel Reconciliation' },
  CanExecuteParcelReconciliation: { module: 'Parcel Reconciliation' },
  CanOverrideParcelReconciliationWindow: { module: 'Parcel Reconciliation' },
  CanReadAccountingAccounts: { module: 'Chart of Accounts' },
  CanCreateAccountingAccounts: { module: 'Chart of Accounts' },
  CanUpdateAccountingAccounts: { module: 'Chart of Accounts' },
  CanDeleteAccountingAccounts: { module: 'Chart of Accounts' },
  CanReadAccountingExpenseCategories: { module: 'Expense Category Management' },
  CanCreateAccountingExpenseCategories: { module: 'Expense Category Management' },
  CanUpdateAccountingExpenseCategories: { module: 'Expense Category Management' },
  CanDeleteAccountingExpenseCategories: { module: 'Expense Category Management' },
  CanReadAccountingApprovalPolicies: { module: 'Accounting Approval Policies' },
  CanCreateAccountingApprovalPolicies: { module: 'Accounting Approval Policies' },
  CanUpdateAccountingApprovalPolicies: { module: 'Accounting Approval Policies' },
  CanDeleteAccountingApprovalPolicies: { module: 'Accounting Approval Policies' },
  CanReadAccountingBankAccounts: { module: 'Bank Account Management' },
  CanCreateAccountingBankAccounts: { module: 'Bank Account Management' },
  CanUpdateAccountingBankAccounts: { module: 'Bank Account Management' },
  CanDeleteAccountingBankAccounts: { module: 'Bank Account Management' },
  CanReadAccountingTaxProfiles: { module: 'Tax Profile Management' },
  CanCreateAccountingTaxProfiles: { module: 'Tax Profile Management' },
  CanUpdateAccountingTaxProfiles: { module: 'Tax Profile Management' },
  CanDeleteAccountingTaxProfiles: { module: 'Tax Profile Management' },
  CanReadAccountingTaxComponents: { module: 'Tax Component Management' },
  CanCreateAccountingTaxComponents: { module: 'Tax Component Management' },
  CanUpdateAccountingTaxComponents: { module: 'Tax Component Management' },
  CanDeleteAccountingTaxComponents: { module: 'Tax Component Management' },
  CanComputeTaxes: { subdomain: 'Taxation', module: 'Tax Computation & Filing' },
  CanCreateTaxFilingPeriod: { subdomain: 'Taxation', module: 'Tax Computation & Filing' },
  CanMarkTaxFilingPeriodUnderReview: { subdomain: 'Taxation', module: 'Tax Computation & Filing' },
  CanSubmitTaxFilingPeriod: { subdomain: 'Taxation', module: 'Tax Computation & Filing' },
  CanCloseTaxFilingPeriod: { subdomain: 'Taxation', module: 'Tax Computation & Filing' },
  CanMarkTaxItemReadyForFiling: { subdomain: 'Taxation', module: 'Tax Computation & Filing' },
  CanMarkTaxItemFiled: { subdomain: 'Taxation', module: 'Tax Computation & Filing' },
  CanExcludeTaxItemFromFiling: { subdomain: 'Taxation', module: 'Tax Computation & Filing' },
};
