export {
  SELF_SERVICE_INPUT_CLASS,
  SELF_SERVICE_LABEL_CLASS,
  SELF_SERVICE_SELECT_CONTENT_CLASS,
  SELF_SERVICE_SELECT_TRIGGER_CLASS,
  SELF_SERVICE_TEXTAREA_CLASS,
} from './self-service-field-styles';
