import type { ParcelFullDetails, ParcelSearchRow } from '../../api/parcel.api';
import type { PickupOtpVerification } from './use-pickup-otp-verification';

type StaffOption = { id: string; fullname: string };
type CardOption = { id: string; name: string };
type CustomerCard = { id: string; cardName: string; cardNumber: string };

export type PickupVerificationDialogProps = {
  open: boolean;
  parcel: ParcelSearchRow | null;
  onClose: () => void;
  pickerStaffId: string;
  onPickerStaffIdChange: (value: string) => void;
  staffOptions: StaffOption[];
  staffLocationName: string | null;
  isPickupQueueEnabled: boolean;
  isPickupOtpRequired: boolean;
  hasPickupQueue: boolean;
  parcelDetails: ParcelFullDetails | undefined;
  formatDateTime: (value: string | null | undefined) => string;
  mainCardMode: string;
  onMainCardModeChange: (value: string) => void;
  mainExistingCardRecordId: string;
  onMainExistingCardRecordIdChange: (value: string) => void;
  mainNewCardTypeId: string;
  onMainNewCardTypeIdChange: (value: string) => void;
  mainNewCardNumber: string;
  onMainNewCardNumberChange: (value: string) => void;
  mainReceiverCards: CustomerCard[];
  handoverTarget: string;
  onHandoverTargetChange: (value: string) => void;
  phoneSlot: 'primary' | 'secondary';
  onPhoneSlotChange: (value: 'primary' | 'secondary') => void;
  secondNewName: string;
  onSecondNewNameChange: (value: string) => void;
  secondNewPhone: string;
  onSecondNewPhoneChange: (value: string) => void;
  secondCardMode: string;
  onSecondCardModeChange: (value: string) => void;
  secondExistingCardRecordId: string;
  onSecondExistingCardRecordIdChange: (value: string) => void;
  secondNewCardTypeId: string;
  onSecondNewCardTypeIdChange: (value: string) => void;
  secondNewCardNumber: string;
  onSecondNewCardNumberChange: (value: string) => void;
  secondReceiverCards: CustomerCard[];
  cardOptions: CardOption[];
  otp: PickupOtpVerification;
  isSaving: boolean;
  isLoading: boolean;
  hasLoadError: boolean;
  onRequestHomeDelivery: () => Promise<void>;
  onConfirmDelivered: () => Promise<void>;
};
