import { PermissionKeys } from '@/shared/permissions/constants';
import type { DashboardWidget } from './types';

export const DASHBOARD_WIDGETS: DashboardWidget[] = [
  {
    id: 'ops-bookings',
    title: 'Booking Pipeline',
    description: 'Track parcel booking throughput and open queues.',
    domain: 'Operations',
    subdomain: 'Parcel Lifecycle',
    module: 'Booking & Shipping',
    requiredPermissions: [PermissionKeys.CanReadParcels],
    priority: 100,
    route: '/parcels',
  },
  {
    id: 'ops-receiving',
    title: 'Receiving Workbench',
    description: 'Monitor incoming and scan-to-receive readiness.',
    domain: 'Operations',
    subdomain: 'Parcel Lifecycle',
    module: 'Parcel Receiving',
    requiredPermissions: [PermissionKeys.CanReadParcelIncoming],
    priority: 90,
    route: '/parcels/in-transit/incoming',
  },
  {
    id: 'ops-delivery',
    title: 'Delivery Dispatch Board',
    description: 'Manage delivery dispatch and rider assignment status.',
    domain: 'Operations',
    subdomain: 'Delivery Execution',
    module: 'Last Mile Delivery',
    requiredPermissions: [PermissionKeys.CanDispatchForDelivery],
    priority: 85,
    route: '/parcels/home-delivery/dispatch',
  },
  {
    id: 'commercial-customers',
    title: 'Customer Portfolio',
    description: 'Access customer profile and lifecycle activity.',
    domain: 'Commercial',
    subdomain: 'Customer Lifecycle',
    module: 'Customer Master Management',
    requiredPermissions: [PermissionKeys.CanReadCustomers],
    priority: 100,
    route: '/customers',
  },
  {
    id: 'commercial-campaigns',
    title: 'Campaign Operations',
    description: 'Create and approve outbound engagement campaigns.',
    domain: 'Commercial',
    subdomain: 'Customer Engagement',
    module: 'Notification Orchestration',
    requiredPermissions: [PermissionKeys.CanReadNotificationHub],
    priority: 90,
    route: '/notification-hub/campaigns',
  },
  {
    id: 'finance-cash',
    title: 'Cash Confirmation Cycle',
    description: 'Review daily cash confirmations and posting queue.',
    domain: 'Finance',
    subdomain: 'Cash Operations',
    module: 'Cashier Session Management',
    requiredPermissions: [PermissionKeys.CanReadCashierSessions],
    priority: 100,
    route: '/cashier/sessions/active',
  },
  {
    id: 'finance-accounting',
    title: 'General Ledger Control',
    description: 'Operate accounting journals and posting controls.',
    domain: 'Finance',
    subdomain: 'Financial Accounting',
    module: 'General Ledger & Controls',
    requiredPermissions: [PermissionKeys.CanReadAccounting],
    priority: 95,
    route: '/accounting',
  },
  {
    id: 'finance-reconciliation',
    title: 'Reconciliation Monitor',
    description: 'Track reconciliation session and settlement progress.',
    domain: 'Finance',
    subdomain: 'Reconciliation',
    module: 'Operational Reconciliation',
    requiredPermissions: [PermissionKeys.CanReadReconciliation],
    priority: 85,
    route: '/reconciliation',
  },
  {
    id: 'supply-inventory',
    title: 'Inventory Control Center',
    description: 'Monitor stock levels, transfers, and replenishment.',
    domain: 'Supply Chain',
    subdomain: 'Inventory Management',
    module: 'Inventory Control',
    requiredPermissions: [PermissionKeys.CanReadInventoryOverview],
    priority: 100,
    route: '/inventory',
  },
  {
    id: 'supply-procurement',
    title: 'Procurement Workbench',
    description: 'Oversee purchase requests, approvals, and suppliers.',
    domain: 'Supply Chain',
    subdomain: 'Procurement',
    module: 'Sourcing & Purchasing',
    requiredPermissions: [PermissionKeys.CanReadProcurement],
    priority: 90,
    route: '/procurement',
  },
  {
    id: 'human-workforce',
    title: 'Workforce Administration',
    description: 'Maintain employee records and workforce structure.',
    domain: 'Human Capital',
    subdomain: 'Workforce Administration',
    module: 'Employee Administration',
    requiredPermissions: [PermissionKeys.CanListEmployees],
    priority: 100,
    route: '/hr/employees',
  },
  {
    id: 'human-payroll',
    title: 'Payroll Cycle Oversight',
    description: 'Track payroll cycles, inputs, and approvals.',
    domain: 'Human Capital',
    subdomain: 'Compensation & Payroll',
    module: 'Payroll Operations',
    requiredPermissions: [PermissionKeys.CanReadPayrollRun],
    priority: 90,
    route: '/payroll/cycles',
  },
  {
    id: 'tech-platform',
    title: 'Platform Configuration',
    description: 'Manage organization-level setup and platform controls.',
    domain: 'Technology',
    subdomain: 'Platform Administration',
    module: 'Platform Configuration',
    requiredPermissions: [PermissionKeys.CanReadCompanyProfile],
    priority: 100,
    route: '/settings/company',
  },
  {
    id: 'tech-it-support',
    title: 'IT Service Desk',
    description: 'Monitor and triage IT support ticket operations.',
    domain: 'Technology',
    subdomain: 'Service Operations',
    module: 'IT Support Desk',
    requiredPermissions: [PermissionKeys.CanReadItSupportTickets],
    priority: 90,
    route: '/it-support/tickets',
  },
  {
    id: 'governance-rbac',
    title: 'Access Governance',
    description: 'Control role design and permission assignments.',
    domain: 'Governance',
    subdomain: 'Access Governance',
    module: 'Role & Permission Governance',
    requiredPermissions: [PermissionKeys.CanReadRoles],
    priority: 100,
    route: '/roles',
  },
  {
    id: 'governance-audit',
    title: 'Audit Control Tower',
    description: 'Review audit trail and suspicious activity.',
    domain: 'Governance',
    subdomain: 'Audit & Compliance',
    module: 'Audit Trail',
    requiredPermissions: [PermissionKeys.CanListAuditLogs],
    priority: 90,
    route: '/reports/audit/user',
  },
  {
    id: 'insights-reporting',
    title: 'Enterprise Reporting',
    description: 'Access standardized enterprise reports.',
    domain: 'Insights',
    subdomain: 'Enterprise Reporting',
    module: 'Enterprise Reports',
    requiredPermissions: [PermissionKeys.CanReadReportsHub],
    priority: 100,
    route: '/reports',
  },
  {
    id: 'insights-analytics',
    title: 'Analytics Workspace',
    description: 'Analyze performance trends and operational metrics.',
    domain: 'Insights',
    subdomain: 'Performance Analytics',
    module: 'Business Analytics',
    requiredPermissions: [PermissionKeys.CanViewBasicAnalytics],
    priority: 90,
    route: '/analytics',
  },
];
