name: Build and Deploy Docker Image

on:
  pull_request:
    branches:
      - development

env:
  DOCKER_IMAGE_NAME: kumateck/vipex_app_dev
  CONTAINER_NAME: vipex_app_dev
  HOST_PORT: 11000
  CONTAINER_PORT: 3000
  APP_BASE_URL: https://test.app.vipexparcel.com
  RESET_LINK_BASE_URL: https://test.app.vipexparcel.com
  INVITE_LINK_BASE_URL: https://test.app.vipexparcel.com

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          file: dev.Dockerfile
          tags: ${{ env.DOCKER_IMAGE_NAME }}:latest
          no-cache: true

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DOCKER_IMAGE_NAME: ${{ env.DOCKER_IMAGE_NAME }}
          CONTAINER_NAME: ${{ env.CONTAINER_NAME }}
          HOST_PORT: ${{ env.HOST_PORT }}
          CONTAINER_PORT: ${{ env.CONTAINER_PORT }}
          APP_BASE_URL: ${{ env.APP_BASE_URL }}
          RESET_LINK_BASE_URL: ${{ env.RESET_LINK_BASE_URL }}
          INVITE_LINK_BASE_URL: ${{ env.INVITE_LINK_BASE_URL }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          DISCORD_WEBHOOK_PRODUCTION: ${{ secrets.DISCORD_WEBHOOK_PRODUCTION }}
          DISCORD_WEBHOOK_DEVELOPMENT: ${{ secrets.DISCORD_WEBHOOK_DEVELOPMENT }}
          MINIO_ENDPOINT: ${{ secrets.MINIO_ENDPOINT }}
          MINIO_REGION: ${{ secrets.MINIO_REGION }}
          MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
          MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
          MINIO_BUCKET: ${{ secrets.MINIO_BUCKET }}
          MINIO_FORCE_PATH_STYLE: ${{ secrets.MINIO_FORCE_PATH_STYLE }}

        run: |
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh -o StrictHostKeyChecking=no "${{ secrets.SSH_USERNAME }}"@"${{ secrets.SSH_HOST }}" -p "${{ secrets.SSH_PORT }}" << EOF
            echo "Logging in to Docker Hub"
            docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_PASSWORD }}'

            echo "Pulling the latest Docker image: ${DOCKER_IMAGE_NAME}:latest"
            docker pull "${DOCKER_IMAGE_NAME}:latest"

            echo "Stopping and removing the existing container if it exists"
            if [ \$(docker ps -a | grep "${CONTAINER_NAME}" | wc -l) -gt 0 ]; then
              docker stop "${CONTAINER_NAME}"
              docker rm "${CONTAINER_NAME}"
            fi

            echo "Ensuring 'sail' network exists"
            docker network inspect sail >/dev/null 2>&1 || docker network create sail

            echo "Pruning unused Docker images"
            docker image prune -a -f

            echo "Running the new Docker container with env vars"
            docker run -d --restart always --net sail \
              -p "${HOST_PORT}:${CONTAINER_PORT}" \
              --name "${CONTAINER_NAME}" \
              -e DATABASE_URL='postgres://${{ secrets.DB_USERNAME }}:${{ secrets.DB_PASSWORD }}@postgres_db:5432/vipexdevdb' \
              -e JWT_SECRET='${{ secrets.JWT_SECRET }}' \
              -e EMAIL_USER='dkadusei@kumateck.com' \
              -e EMAIL_PASSWORD='Password' \
              -e NODE_ENV='production' \
              -e APP_ENV='development' \
              -e APP_BASE_URL='${APP_BASE_URL}' \
              -e RESET_LINK_BASE_URL='${RESET_LINK_BASE_URL}' \
              -e INVITE_LINK_BASE_URL='${INVITE_LINK_BASE_URL}' \
              -e SENTRY_DSN='${SENTRY_DSN}' \
              -e DISCORD_WEBHOOK_PRODUCTION='${DISCORD_WEBHOOK_PRODUCTION}' \
              -e DISCORD_WEBHOOK_DEVELOPMENT='${DISCORD_WEBHOOK_DEVELOPMENT}' \
              -e MINIO_ENDPOINT='${MINIO_ENDPOINT}' \
              -e MINIO_REGION='${MINIO_REGION}' \
              -e MINIO_ACCESS_KEY='${MINIO_ACCESS_KEY}' \
              -e MINIO_SECRET_KEY='${MINIO_SECRET_KEY}' \
              -e MINIO_BUCKET='${MINIO_BUCKET}' \
              -e MINIO_FORCE_PATH_STYLE='${MINIO_FORCE_PATH_STYLE}' \
              "${DOCKER_IMAGE_NAME}:latest"
          EOF
